USE thankQ3_Reporter;

IF OBJECT_ID('MyView_Contacts', 'V') IS NULL
  EXEC('CREATE VIEW dbo.MyView_Contacts AS SELECT NULL AS DUMMY;')
GO


ALTER VIEW MyView_Contacts AS
-- --------------------------------------------------------------
WITH
ones AS ( 
SELECT * FROM (VALUES (0),(1),(2),(3),(4),(5),(6),(7),(8),(9)) AS numbers(x) 
)
-- --------------------------------------------------------------
,generation_def AS(
SELECT *
FROM (VALUES
    (0, 1824, 'ANCIENT', '01.AC')
    ,(1825, 1844, 'EARLY COLONIAL', '02.EC')
    ,(1845, 1864, 'MID COLONIAL', '03.MC')
    ,(1865, 1884, 'LATE COLONIAL', '04.LC')
    ,(1885, 1904, 'HARD TIMERS', '05.HT')
    ,(1905, 1924, 'FEDERATION', '06.F')
    ,(1925, 1944, 'SILENT', '07.S')
    ,(1945, 1964, 'BABY BOOMERS', '08.BB')
    ,(1965, 1979, 'GENERATION X', '09.X')
    ,(1980, 1994, 'GENERATION Y', '10.Y')
    ,(1995, 2009, 'GENERATION Z', '11.Z')
    ,(2010, 9999, 'MILLENIALS', '12.M')  ) AS generation(y1,y2,gen,gen_abr) 
)
-- --------------------------------------------------------------
,generation AS (
SELECT CY=n.x, GEN=g.gen, GEN_ABR=g.gen_abr
FROM
    (SELECT x=1000*o1000.x + 100*o100.x + 10*o10.x + o1.x
    FROM ones o1, ones o10, ones o100, ones o1000 ) n
    LEFT JOIN generation_def g on(n.x>=g.y1 AND n.x<=g.y2)
WHERE n.x BETWEEN 1 AND YEAR(CURRENT_TIMESTAMP)
)
-- --------------------------------------------------------------
,cte_contacts AS (
SELECT C1.SERIALNUMBER, C1.CREATED
   , FULLNAME=CONCAT(
      IIF(RTRIM(C1.TITLE)='' OR C1.TITLE IS NULL,'',RTRIM(C1.TITLE)+' ')
      ,IIF(RTRIM(C1.FIRSTNAME)='' OR C1.FIRSTNAME IS NULL,'',RTRIM(C1.FIRSTNAME)+' ')
      ,IIF(RTRIM(C1.OTHERINITIAL)='' OR C1.OTHERINITIAL IS NULL,'',RTRIM(C1.OTHERINITIAL)+' '),C1.KEYNAME)
   , C1.CONTACTTYPE, C1.PRIMARYCATEGORY, C1.SOURCE
   , GENDER=IIF(C1.CONTACTTYPE='Organisation','N/A',IIF(C1.GENDER IS NULL OR RTRIM(C1.GENDER )='Missing',NULL,C1.GENDER ))
   , C1.DATEOFBIRTH
   , AGE=IIF(C1.CONTACTTYPE='Organisation',NULL,IIF(C1.DATEOFBIRTH IS NULL,NULL,(DATEDIFF(day,C1.DATEOFBIRTH,CURRENT_TIMESTAMP)+1)/365))
   , GENERATION=C3.GEN, C3.GEN_ABR
   , C1.ADDRESSLINE1, C1.ADDRESSLINE2, SUBURB=C1.ADDRESSLINE3
   , STATE=IIF(UPPER(LTRIM(RTRIM(C1.ADDRESSLINE4))) IN ('VIC','NSW','SA','QLD','WA','TAS','ACT','NT'),UPPER(LTRIM(RTRIM(C1.ADDRESSLINE4))),'O/S')
   , C1.POSTCODE, C1.COUNTRY, C1.EMAILADDRESS
   , ISMAJORDONOR=IIF(C1.MAJORDONOR=-1,'YES',NULL)
   , ISANONYMOUS=IIF(C1.ANONYMOUS=-1,'YES',NULL)
   , ISDONOTMAIL=IIF(C1.DONOTMAIL=-1,'YES',NULL)
   , ISDONOTCALL=IIF(C2.DONOTCALL=-1,'YES',NULL)
   , C1.DONOTMAILREASON, C1.DONOTMAILFROM, C1.DONOTMAILUNTIL
   , MANAGER=CONCAT(
       IIF(C2.CRMPRIMARYMANAGER IS NULL OR RTRIM(C2.CRMPRIMARYMANAGER)='','','[P]' + C2.CRMPRIMARYMANAGER)
        ,IIF(NOT(C2.CRMPRIMARYMANAGER IS NULL OR RTRIM(C2.CRMPRIMARYMANAGER)='') AND NOT(C2.CRMSECONDARYMANAGER IS NULL OR RTRIM(C2.CRMSECONDARYMANAGER)=''),', ','')
        ,IIF(C2.CRMSECONDARYMANAGER IS NULL OR RTRIM(C2.CRMSECONDARYMANAGER)='','','[S]'+C2.CRMSECONDARYMANAGER)
        )
FROM
    TBL_CONTACT C1
    LEFT JOIN TBL_CONTACTATTRIBUTE C2 ON (C1.SERIALNUMBER = C2.SERIALNUMBER)
    LEFT JOIN generation C3 ON (YEAR(C1.DATEOFBIRTH) = C3.CY)
WHERE C1.CONTACTTYPE <> 'ADDRESS'
)
-- --------------------------------------------------------------
select * from cte_contacts
