USE thankQ3_Reporter;

IF OBJECT_ID('MyView_Payments', 'V') IS NULL
  EXEC('CREATE VIEW dbo.MyView_Payments AS SELECT NULL AS DUMMY;')
GO


ALTER VIEW MyView_Payments AS
-- --------------------------------------------------------------
WITH
cte_sourcecode AS(
SELECT
  SOURCECODE,SOURCETYPE
  ,IIF(SOURCETYPE LIKE 'Sponsorship', 'P',IIF(SOURCETYPE LIKE 'Merch%', 'M',IIF(SOURCETYPE LIKE 'Group', 'G',IIF(SOURCETYPE LIKE 'Bequest', 'B'
  ,IIF(ADDITIONALCODE3 IS NULL OR RTRIM(ADDITIONALCODE3) = '', 'U','C'))))) AS SOURCECATEGORY
  ,ADDITIONALCODE1 AS QBCODE,ADDITIONALCODE5 AS QBCLASS,ADDITIONALCODE3 AS CAMPAIGN
  ,DEFAULT_DES1=DESTINATIONCODE,DEFAULT_DES2=DESTINATIONCODE2
  ,SOURCEDESCRIPTION,SOURCENOTES
  ,ARCHIVE,EXCLUDEFROMDROPDOWN
  ,SOURCECODE_CREATEDBY=CREATEDBY,SOURCECODE_CREATED=CREATED
  ,SOURCECODE_MODIFIEDBY=MODIFIEDBY,SOURCECODE_MODIFIED=MODIFIED
FROM TBL_SOURCECODE)
-- --------------------------------------------------------------
,cte_payments AS (
SELECT
  B1.SERIALNUMBER,B1.PAYMENTAMOUNT,B2.DATEOFPAYMENT,B2.PAYMENTTYPE
  ,ACTUAL_DES1=B1.DESTINATIONCODE,ACTUAL_DES2=B1.DESTINATIONCODE2
  ,B1.SOURCECODE2
  ,B6.*
  ,FY=IIF(MONTH(B2.DATEOFPAYMENT)<7,YEAR(B2.DATEOFPAYMENT),YEAR(B2.DATEOFPAYMENT)+1)
  ,FYMTH=IIF(MONTH(B2.DATEOFPAYMENT)<7,MONTH(B2.DATEOFPAYMENT)+6,MONTH(B2.DATEOFPAYMENT)-6)
  ,CY=YEAR(B2.DATEOFPAYMENT),CYMTH=MONTH(B2.DATEOFPAYMENT),DAY=DAY(B2.DATEOFPAYMENT)
  ,B4.ADMITNAME,B2.RECEIPTNO,B2.REVERSED,B4.APPROVED,B4.STAGE
  ,LAST_PROCESSED=IIF(B1.MODIFIED IS NULL AND B2.MODIFIED IS NULL, B4.MODIFIED, 
    IIF(B1.MODIFIED IS NULL OR B2.MODIFIED IS NULL, ISNULL(B1.MODIFIED,B2.MODIFIED),
      IIF(B1.MODIFIED<B2.MODIFIED,B2.MODIFIED,B1.MODIFIED)))
  ,LAST_PROCESSEDBY=IIF(B1.MODIFIED IS NULL AND B2.MODIFIED IS NULL, B4.MODIFIEDBY, 
    IIF(B1.MODIFIED IS NULL OR B2.MODIFIED IS NULL, ISNULL(B1.MODIFIEDBY,B2.MODIFIEDBY),
      IIF(B1.MODIFIED<B2.MODIFIED,B2.MODIFIEDBY,B1.MODIFIEDBY)))
  ,TRX_ID=CAST(DENSE_RANK() OVER(PARTITION BY B1.SERIALNUMBER ORDER BY B2.DATEOFPAYMENT ASC, CONCAT(B1.SERIALNUMBER,'-',B1.ADMITNAME,'-',B2.RECEIPTNO) ASC) AS INT)
  ,TRX_ID2=( 
    CASE WHEN B2.REVERSED <>2 OR B2.REVERSED IS NULL THEN
        CAST(DENSE_RANK() OVER(PARTITION BY B1.SERIALNUMBER ORDER BY B2.DATEOFPAYMENT ASC, CONCAT(B1.SERIALNUMBER,'-',B1.ADMITNAME,'-',B2.RECEIPTNO) ASC) AS INT)
        ELSE NULL END
    )
  ,TRX_ID3=( 
    CASE WHEN B2.REVERSED <>2 OR B2.REVERSED IS NULL THEN
        CAST(DENSE_RANK() OVER(PARTITION BY (CASE WHEN B2.REVERSED <>2 OR B2.REVERSED IS NULL THEN 1 ELSE 0 END) ORDER BY B2.DATEOFPAYMENT ASC, CONCAT(B1.SERIALNUMBER,'-',B1.ADMITNAME,'-',B2.RECEIPTNO) ASC) AS INT)
        ELSE NULL END
    )

FROM
  TBL_BATCHITEMSPLIT        B1
  LEFT JOIN TBL_BATCHITEM   B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
  LEFT JOIN TBL_BATCHHEADER B4 ON (B2.ADMITNAME = B4.ADMITNAME)
  LEFT JOIN cte_sourcecode  B6 ON (B1.SOURCECODE = B6.SOURCECODE)
WHERE
  (B2.REVERSED IS NULL OR NOT(B2.REVERSED=1 OR B2.REVERSED=-1)) -- Full reversal and re-entry should be excluded all time
--    AND (B4.STAGE ='Batch Approved')
--    AND CAST(B2.DATEOFPAYMENT AS DATE) <= CAST(@MYDATE AS DATE)
)
-- --------------------------------------------------------------
select * from cte_payments
