-- auto-generated definition
CREATE TABLE BATCHITEM
(
  ADMITNAME                  VARCHAR(50)   NOT NULL,
  RECEIPTNO                  VARCHAR(150)  NOT NULL,
  SERIALNUMBER               VARCHAR(50)   NOT NULL,
  DATEOFPAYMENT              DATETIME,
  DATEPOSTED                 DATETIME,
  PAYMENTTYPE                VARCHAR(50),
  PAYMENTAMOUNT              MONEY,
  PAYMENTAMOUNTNETT          MONEY,
  GSTAMOUNT                  MONEY,
  MANUALRECEIPTNO            VARCHAR(50),
  TREATASANON                SMALLINT,
  TEMPDESTINATIONCODE        VARCHAR(25),
  TEMPDESTINATIONCODE2       VARCHAR(25),
  TEMPSOURCECODE             VARCHAR(25),
  TEMPSOURCECODE2            VARCHAR(25),
  TEMPCAMPAIGNYEAR           INT,
  TEMPRECEIPTREQUIRED        VARCHAR(3),
  TEMPRECEIPTSUMMARY         VARCHAR(3),
  TEMPTAXCLAIMABLE           VARCHAR(3),
  TEMPTRANSTYPE              VARCHAR(20),
  TEMPPLEDGEPLAN             VARCHAR(20),
  TEMPPLEDGETYPE             VARCHAR(20),
  TEMPFREQUENCY              VARCHAR(20),
  TEMPSTARTDATE              DATETIME,
  TEMPINSTALMENTS            REAL,
  PAYMENTRATIO               MONEY,
  NARRATIVE                  VARCHAR(255),
  INCLUDEINTHANKYOU          SMALLINT,
  ACCOUNTNAME                VARCHAR(50),
  SORTCODE                   VARCHAR(50),
  ACCOUNTNUMBER              VARCHAR(20),
  ROLLNUMBER                 VARCHAR(20),
  TEXT1                      VARCHAR(255),
  TEXT2                      VARCHAR(255),
  BANKNAME                   VARCHAR(100),
  BANKADDRESS                VARCHAR(255),
  BANKPOSTCODE               VARCHAR(10),
  CREDITCARDTYPE             VARCHAR(20),
  CREDITCARDNUMBER           VARCHAR(100),
  CREDITCARDHOLDER           VARCHAR(100),
  CREDITCARDEXPIRY           VARCHAR(8),
  CREDITCARDISSUENUMBER      VARCHAR(5),
  CREDITCARDAUTHCODE         VARCHAR(20),
  CREDITCARDMETHOD           VARCHAR(50),
  CHEQUENUMBER               VARCHAR(10),
  CREATED                    DATETIME,
  CREATEDBY                  VARCHAR(50),
  MODIFIED                   DATETIME,
  MODIFIEDBY                 VARCHAR(50),
  NOTES                      VARCHAR(8000),
  RESULT                     VARCHAR(255),
  SUCCESSFAILURE             SMALLINT,
  APPLYJOINTSALUTATION       SMALLINT,
  TITLE                      VARCHAR(30),
  FIRSTNAME                  VARCHAR(50),
  KEYNAME                    VARCHAR(100),
  POSTCODE                   VARCHAR(26),
  ADDRESSLINE1               VARCHAR(255),
  ADDRESSLINE2               VARCHAR(100),
  ADDRESSLINE3               VARCHAR(100),
  ADDRESSLINE4               VARCHAR(100),
  ENVELOPESALUTATION         VARCHAR(100),
  LETTERSALUTATION           VARCHAR(100),
  REVERSED                   SMALLINT,
  CREDITCARDTOKEN            VARCHAR(50),
  CREDITCARDMASKED           VARCHAR(100),
  REMAININGAMOUNT            MONEY,
  REMAININGAMOUNTNETT        MONEY,
  REMAININGGSTAMOUNT         MONEY,
  ORGRECEIPTNO               VARCHAR(150),
  OWNERCODE                  INT DEFAULT 0 NOT NULL,
  ADDRESSTYPE                VARCHAR(50),
  DAYTELEPHONE               VARCHAR(30),
  EVENINGTELEPHONE           VARCHAR(30),
  FAXNUMBER                  VARCHAR(30),
  MOBILENUMBER               VARCHAR(30),
  EMAILADDRESS               VARCHAR(255),
  DATEOFBIRTH                DATETIME,
  RELATIONTITLE              VARCHAR(30),
  RELATIONFIRSTNAME          VARCHAR(50),
  RELATIONKEYNAME            VARCHAR(100),
  RELATIONSHIP               VARCHAR(50),
  RELATIONSHIPREVERSE        VARCHAR(50),
  ADDRESSID                  VARCHAR(50),
  IC                         VARCHAR(50),
  ICTYPE                     VARCHAR(255),
  TOKENGATEWAY               VARCHAR(50),
  DATESETTLED                DATETIME,
  BANKREFERENCE              VARCHAR(50),
  DATAIMPORTBARCODEID        VARCHAR(50),
  PAYMENTGATEWAYRESPONSECODE VARCHAR(50),
  CONSTRAINT PK_BATCHITEM
  PRIMARY KEY (ADMITNAME, RECEIPTNO, SERIALNUMBER, OWNERCODE)
)
GO
CREATE INDEX IX_BATCHITEM_ACCOUNTNAME
  ON BATCHITEM (ACCOUNTNAME)
GO
CREATE INDEX IX_BATCHITEM_ACCOUNTNUMBER
  ON BATCHITEM (ACCOUNTNUMBER)
GO
CREATE INDEX IX_BATCHITEM_BANKADDRESS
  ON BATCHITEM (BANKADDRESS)
GO
CREATE INDEX IX_BATCHITEM_BANKNAME
  ON BATCHITEM (BANKNAME)
GO
CREATE INDEX IX_BATCHITEM_BANKPOSTCODE
  ON BATCHITEM (BANKPOSTCODE)
GO
CREATE INDEX IX_BATCHITEM_CHEQUENUMBER
  ON BATCHITEM (CHEQUENUMBER)
GO
CREATE INDEX IX_BATCHITEM_MODIFIEDBYCREATEDBY
  ON BATCHITEM (MODIFIEDBY, CREATEDBY)
GO
CREATE INDEX IX_BATCHITEM_REVERSED
  ON BATCHITEM (REVERSED)
GO
CREATE INDEX IX_BATCHITEM_REMAININGAMOUNT
  ON BATCHITEM (REMAININGAMOUNT)
GO
CREATE INDEX IX_BATCHITEM_CREDITCARDEXPIRY
  ON BATCHITEM (CREDITCARDEXPIRY)
GO
CREATE INDEX IX_BATCHITEM_CREDITCARDHOLDER
  ON BATCHITEM (CREDITCARDHOLDER)
GO
CREATE INDEX IX_BATCHITEM_ORGRECEIPTNO
  ON BATCHITEM (ORGRECEIPTNO)
GO
CREATE INDEX IX_BATCHITEM_CREDITCARDMETHOD
  ON BATCHITEM (CREDITCARDMETHOD)
GO
CREATE INDEX IX_BATCHITEM_CREDITCARDNUMBER
  ON BATCHITEM (CREDITCARDNUMBER)
GO
CREATE INDEX IX_BATCHITEM_CREDITCARDTYPE
  ON BATCHITEM (CREDITCARDTYPE)
GO
CREATE INDEX IX_BATCHITEM_DATEOFPAYMENT
  ON BATCHITEM (DATEOFPAYMENT)
GO
CREATE INDEX IX_BATCHITEM_DATEPOSTED
  ON BATCHITEM (DATEPOSTED, ADMITNAME, RECEIPTNO, SERIALNUMBER, DATEOFPAYMENT, REVERSED)
GO
CREATE INDEX IX_BATCHITEM_CREATED
  ON BATCHITEM (CREATED)
GO
CREATE INDEX IX_BATCHITEM_MANUALRECEIPTNO
  ON BATCHITEM (MANUALRECEIPTNO)
GO
CREATE INDEX IX_BATCHITEM_CREDITCARDTOKEN
  ON BATCHITEM (CREDITCARDTOKEN, PAYMENTTYPE, PAYMENTAMOUNT)
GO
CREATE INDEX IX_BATCHITEM_NARRATIVE
  ON BATCHITEM (NARRATIVE)
GO
CREATE INDEX IX_BATCHITEM_PAYMENTAMOUNT
  ON BATCHITEM (PAYMENTAMOUNT)
GO
CREATE INDEX IX_BATCHITEM_PAYMENTAMOUNTNETT
  ON BATCHITEM (PAYMENTAMOUNTNETT)
GO
CREATE INDEX IX_BATCHITEM_IC
  ON BATCHITEM (IC)
GO
CREATE INDEX IX_BATCHITEM_PAYMENTTYPE
  ON BATCHITEM (PAYMENTTYPE, ADMITNAME, PAYMENTAMOUNT)
GO
CREATE INDEX IX_BATCHITEM_SORTCODE
  ON BATCHITEM (SORTCODE)
GO
CREATE INDEX IX_BATCHITEM_TREATASANON
  ON BATCHITEM (TREATASANON)
GO
CREATE INDEX IX_BATCHITEM_SERIALNUMBERDATEPOSTED
  ON BATCHITEM (SERIALNUMBER, DATEPOSTED, ADMITNAME, RECEIPTNO, OWNERCODE)
GO
CREATE INDEX IX_BATCHITEM_PAYMENTAMOUNT_REVERSED
  ON BATCHITEM (PAYMENTAMOUNT, REVERSED, ADMITNAME, RECEIPTNO, SERIALNUMBER)
GO
CREATE INDEX IX_BATCHITEM_RECEIPTNO
  ON BATCHITEM (RECEIPTNO, ADMITNAME, SERIALNUMBER, OWNERCODE)
GO
