-- auto-generated definition
CREATE TABLE BATCHHEADER
(
  ADMITNAME              VARCHAR(50)   NOT NULL,
  BATCHTYPE              VARCHAR(50),
  BATCHDESCRIPTION       VARCHAR(255),
  CURRENCY               VARCHAR(25),
  EXPECTEDNUMBEROFITEMS  FLOAT,
  EXPECTEDVALUE          MONEY,
  ACCOUNTREFERENCE       VARCHAR(25),
  PAYINGINREFERENCE      VARCHAR(25),
  SENTTOACCOUNTS         SMALLINT,
  RECEIPTSPREPARED       SMALLINT,
  DEFAULTDATEOFPAYMENT   DATETIME,
  DEFAULTPAYMENTTYPE     VARCHAR(25),
  DEFAULTPAYMENTAMOUNT   MONEY,
  DEFAULTTAXCLAIMABLE    VARCHAR(4),
  DEFAULTRECEIPTREQUIRED VARCHAR(4),
  DEFAULTDESTINATION     VARCHAR(25),
  DEFAULTDESTINATION2    VARCHAR(25),
  DEFAULTSOURCE          VARCHAR(25),
  DEFAULTSOURCE2         VARCHAR(25),
  DEFAULTCAMPAIGNYEAR    INT,
  DEFAULTINCLUDETEXTRULE VARCHAR(50),
  APPROVED               DATETIME,
  APPROVEDBY             VARCHAR(50),
  CREATED                DATETIME,
  CREATEDBY              VARCHAR(50),
  MODIFIED               DATETIME,
  MODIFIEDBY             VARCHAR(50),
  CURRENTLYEDITEDBY      VARCHAR(50),
  DEFAULTRECEIPTSUMMARY  VARCHAR(3),
  SUBMITTED              DATETIME,
  SUBMITTEDBY            VARCHAR(50),
  FUNDSTATSCALCULATED    SMALLINT,
  NOTES                  VARCHAR(8000),
  OWNERCODE              INT DEFAULT 0 NOT NULL,
  EFTSUBMITTED           DATETIME,
  EFTSUBMITTEDBY         VARCHAR(50),
  CONSTRAINT PK_BATCHHEADER
  PRIMARY KEY (ADMITNAME, OWNERCODE)
)
GO
CREATE INDEX IX_BATCHHEADER_DEFAULTRECEIPTSUMMARY
  ON BATCHHEADER (DEFAULTRECEIPTSUMMARY)
GO
CREATE INDEX IX_BATCHHEADER_ACCOUNTREF
  ON BATCHHEADER (ACCOUNTREFERENCE)
GO
CREATE INDEX IX_BATCHHEADER_APPROVED
  ON BATCHHEADER (APPROVED)
GO
CREATE INDEX IX_BATCHHEADER_APPROVEDBY
  ON BATCHHEADER (APPROVEDBY)
GO
CREATE INDEX IX_BATCHHEADER_SUBMITTED
  ON BATCHHEADER (SUBMITTED)
GO
CREATE INDEX IX_BATCHHEADER_SUBMITTEDBY
  ON BATCHHEADER (SUBMITTEDBY)
GO
CREATE INDEX IX_BATCHHEADER_FUNDSTATSCALCULATED
  ON BATCHHEADER (FUNDSTATSCALCULATED)
GO
CREATE INDEX IX_BATCHHEADER_BATCHTYPE
  ON BATCHHEADER (BATCHTYPE)
GO
CREATE INDEX IX_BATCHHEADER_BATCHDESCRIPTION
  ON BATCHHEADER (BATCHDESCRIPTION)
GO
CREATE INDEX IX_BATCHHEADER_MODIFIED_MODIFIEDBY
  ON BATCHHEADER (MODIFIED, MODIFIEDBY, ADMITNAME, OWNERCODE)
GO
CREATE INDEX IX_BATCHHEADER_DEFAULTSOURCE_CREATED
  ON BATCHHEADER (DEFAULTSOURCE, CREATED, ADMITNAME, OWNERCODE)
GO
