-- auto-generated definition
CREATE TABLE BATCHITEMSPLIT
(
  ADMITNAME           VARCHAR(50)  NOT NULL,
  RECEIPTNO           VARCHAR(150) NOT NULL,
  SERIALNUMBER        VARCHAR(50)  NOT NULL,
  LINEID              VARCHAR(50)  NOT NULL,
  SPLITID             VARCHAR(50)  NOT NULL,
  EXTERNALREF         VARCHAR(50),
  EXTERNALREFTYPE     VARCHAR(50),
  TAXCLAIMABLE        VARCHAR(4),
  DESTINATIONCODE     VARCHAR(25),
  DESTINATIONCODE2    VARCHAR(25),
  SOURCECODE          VARCHAR(25),
  SOURCECODE2         VARCHAR(25),
  CAMPAIGNYEAR        INT,
  PAYMENTAMOUNT       MONEY,
  PAYMENTAMOUNTNETT   MONEY,
  GSTAMOUNT           MONEY,
  NEW                 SMALLINT,
  EXISTING            SMALLINT,
  RECOVERED           SMALLINT,
  RANK                INT,
  CREATED             DATETIME,
  CREATEDBY           VARCHAR(50),
  MODIFIED            DATETIME,
  MODIFIEDBY          VARCHAR(50),
  REMAININGAMOUNT     MONEY,
  REMAININGAMOUNTNETT MONEY,
  REMAININGGSTAMOUNT  MONEY,
  CONSTRAINT PK_BATCHITEMSPLIT
  PRIMARY KEY (ADMITNAME, RECEIPTNO, SERIALNUMBER, LINEID, SPLITID)
)
GO
CREATE INDEX IX_BATCHITEMSPLIT_CAMPAIGNYEAR
  ON BATCHITEMSPLIT (CAMPAIGNYEAR)
GO
CREATE INDEX IX_BATCHITEMSPLIT_REMAININGAMOUNT
  ON BATCHITEMSPLIT (REMAININGAMOUNT)
GO
CREATE INDEX IX_BATCHITEMSPLIT_DESTINATIONCODE
  ON BATCHITEMSPLIT (DESTINATIONCODE)
GO
CREATE INDEX IX_BATCHITEMSPLIT_DESTINATIONCODE2
  ON BATCHITEMSPLIT (DESTINATIONCODE2)
GO
CREATE INDEX IX_BATCHITEMSPLIT_GSTAMOUNT
  ON BATCHITEMSPLIT (GSTAMOUNT)
GO
CREATE INDEX IX_BATCHITEMSPLIT_PAYMENTAMOUNT
  ON BATCHITEMSPLIT (PAYMENTAMOUNT)
GO
CREATE INDEX IX_BATCHITEMSPLIT_PAYMENTAMOUNTNETT
  ON BATCHITEMSPLIT (PAYMENTAMOUNTNETT)
GO
CREATE INDEX IX_BATCHITEMSPLIT_SOURCECODE
  ON BATCHITEMSPLIT (SOURCECODE)
GO
CREATE INDEX IX_BATCHITEMSPLIT_SOURCECODE2
  ON BATCHITEMSPLIT (SOURCECODE2, ADMITNAME, RECEIPTNO, SERIALNUMBER, PAYMENTAMOUNT, NEW, EXISTING, RECOVERED, REMAININGAMOUNT)
GO
CREATE INDEX IX_BATCHITEMSPLIT_EXISTING
  ON BATCHITEMSPLIT (EXISTING)
GO
CREATE INDEX IX_BATCHITEMSPLIT_EXTERNALREF
  ON BATCHITEMSPLIT (EXTERNALREF)
GO
CREATE INDEX IX_BATCHITEMSPLIT_EXTERNALREFTYPE
  ON BATCHITEMSPLIT (EXTERNALREFTYPE)
GO
CREATE INDEX IX_BATCHITEMSPLIT_NEW
  ON BATCHITEMSPLIT (NEW)
GO
CREATE INDEX IX_BATCHITEMSPLIT_RANK
  ON BATCHITEMSPLIT (RANK, ADMITNAME, RECEIPTNO, SERIALNUMBER, LINEID, SPLITID, EXTERNALREFTYPE, SOURCECODE)
GO
CREATE INDEX IX_BATCHITEMSPLIT_TAXCLAIMABLE
  ON BATCHITEMSPLIT (TAXCLAIMABLE)
GO
CREATE INDEX IX_BATCHITEMSPLIT_RECOVERED
  ON BATCHITEMSPLIT (RECOVERED)
GO
CREATE INDEX IX_BATCHITEMSPLIT_SERIALNUMBER
  ON BATCHITEMSPLIT (SERIALNUMBER)
GO
CREATE INDEX IX_BATCHITEMSPLIT_SERIALNUMBERNEW
  ON BATCHITEMSPLIT (SERIALNUMBER, NEW)
GO
CREATE INDEX IX_BATCHITEMSPLIT_SERIALNUMBEREXISTING
  ON BATCHITEMSPLIT (SERIALNUMBER, EXISTING)
GO
CREATE INDEX IX_BATCHITEMSPLIT_SERIALNUMBERRECOVERED
  ON BATCHITEMSPLIT (SERIALNUMBER, RECOVERED)
GO
CREATE INDEX IX_BATCHITEMSPLIT_SERIALNUMBERRANK
  ON BATCHITEMSPLIT (SERIALNUMBER, RANK)
GO
CREATE INDEX IX_BATCHITEMSPLIT_EXTERNALREFTYPE_SOURCECODE
  ON BATCHITEMSPLIT (EXTERNALREFTYPE, SOURCECODE, ADMITNAME, RECEIPTNO, SERIALNUMBER, PAYMENTAMOUNT, REMAININGAMOUNT)
GO
CREATE INDEX IX_BATCHITEMSPLIT_SOURCECODE_RANK
  ON BATCHITEMSPLIT (SOURCECODE, RANK, ADMITNAME, RECEIPTNO, SERIALNUMBER, LINEID, SPLITID, EXTERNALREFTYPE, CAMPAIGNYEAR, PAYMENTAMOUNT, GSTAMOUNT, REMAININGAMOUNT, REMAININGGSTAMOUNT, NEW, EXISTING, RECOVERED)
GO
CREATE INDEX IX_BATCHITEMSPLIT_EXTERNALREFTYPE_GSTAMOUNT
  ON BATCHITEMSPLIT (EXTERNALREFTYPE, GSTAMOUNT, ADMITNAME, RECEIPTNO, SERIALNUMBER, SOURCECODE, CAMPAIGNYEAR, PAYMENTAMOUNT, REMAININGAMOUNT)
GO
