-- auto-generated definition
CREATE TABLE BATCHITEMPLEDGE
(
  ADMITNAME           VARCHAR(50)  NOT NULL,
  RECEIPTNO           VARCHAR(150) NOT NULL,
  SERIALNUMBER        VARCHAR(50)  NOT NULL,
  LINEID              VARCHAR(50)  NOT NULL,
  PLEDGEID            VARCHAR(150),
  PLEDGELINENO        INT,
  PAYMENTAMOUNT       MONEY,
  PAYMENTAMOUNTNETT   MONEY,
  GSTAMOUNT           MONEY,
  RECEIPTREQUIRED     VARCHAR(3),
  RECEIPTLETTERID     VARCHAR(25),
  RECEIPTSUMMARY      VARCHAR(3),
  RCPTSUMMARYLETTERID VARCHAR(25),
  CREATED             DATETIME,
  CREATEDBY           VARCHAR(50),
  MODIFIED            DATETIME,
  MODIFIEDBY          VARCHAR(50),
  REMAININGAMOUNT     MONEY,
  REMAININGAMOUNTNETT MONEY,
  REMAININGGSTAMOUNT  MONEY,
  CONSTRAINT PK_BATCHITEMPLEDGE
  PRIMARY KEY (ADMITNAME, RECEIPTNO, SERIALNUMBER, LINEID)
)
GO
CREATE INDEX IX_BATCHITEMPLEDGE_GSTAMOUNT
  ON BATCHITEMPLEDGE (GSTAMOUNT)
GO
CREATE INDEX IX_BATCHITEMPLEDGE_PAYMENTAMOUNT
  ON BATCHITEMPLEDGE (PAYMENTAMOUNT)
GO
CREATE INDEX IX_BATCHITEMPLEDGE_PAYMENTAMOUNTNETT
  ON BATCHITEMPLEDGE (PAYMENTAMOUNTNETT)
GO
CREATE INDEX IX_BATCHITEMPLEDGE_PLEDGEID
  ON BATCHITEMPLEDGE (PLEDGEID, ADMITNAME, RECEIPTNO, SERIALNUMBER, PLEDGELINENO)
GO
CREATE INDEX IX_BATCHITEMPLEDGE_PLEDGELINENO
  ON BATCHITEMPLEDGE (PLEDGELINENO)
GO
CREATE INDEX IX_BATCHITEMPLEDGE_RCPTSUMMARYLETTERID
  ON BATCHITEMPLEDGE (RCPTSUMMARYLETTERID)
GO
CREATE INDEX IX_BATCHITEMPLEDGE_RECEIPTLETTERID
  ON BATCHITEMPLEDGE (RECEIPTLETTERID)
GO
CREATE INDEX IX_BATCHITEMPLEDGE_RECEIPTREQUIRED
  ON BATCHITEMPLEDGE (RECEIPTREQUIRED)
GO
CREATE INDEX IX_BATCHITEMPLEDGE_RECEIPTSUMMARY
  ON BATCHITEMPLEDGE (RECEIPTSUMMARY)
GO
CREATE INDEX IX_BATCHITEMPLEDGE_REMAININGAMOUNT
  ON BATCHITEMPLEDGE (REMAININGAMOUNT)
GO
CREATE INDEX IX_BATCHITEMPLEDGE_SERIALNUMBER
  ON BATCHITEMPLEDGE (SERIALNUMBER, ADMITNAME, RECEIPTNO, LINEID, RECEIPTREQUIRED, RECEIPTLETTERID, RECEIPTSUMMARY, RCPTSUMMARYLETTERID)
GO
CREATE INDEX IX_BATCHITEMPLEDGE_RECEIPTNO
  ON BATCHITEMPLEDGE (RECEIPTNO)
GO
