-- auto-generated definition
CREATE TABLE COMMUNICATION
(
  COMMUNICATIONREF    VARCHAR(50)   NOT NULL,
  SERIALNUMBER        VARCHAR(50)   NOT NULL,
  COMMUNICATIONTYPE   VARCHAR(50),
  EXTERNALREF         VARCHAR(50),
  EXTERNALREFTYPE     VARCHAR(50),
  CRMFLAG             VARCHAR(3),
  DATEOFCOMMUNICATION DATETIME,
  SUBJECT             VARCHAR(255),
  NOTES               VARCHAR(MAX),
  CREATED             DATETIME,
  CREATEDBY           VARCHAR(50),
  MODIFIED            DATETIME,
  MODIFIEDBY          VARCHAR(50),
  PRIORITY            VARCHAR(50),
  ATTACHMENTICON      INT,
  RECORDOWNER         VARCHAR(50),
  ACCESSRIGHTS        VARCHAR(255),
  CONFIDENTIAL        SMALLINT,
  RESPONSE            VARCHAR(50),
  CATEGORY            VARCHAR(50),
  TIMEOFCOMMUNICATION VARCHAR(10),
  OWNERCODE           INT DEFAULT 0 NOT NULL,
  STICKY              BIT,
  REPLY               VARCHAR(1000),
  REPLYDATETIME       DATETIME,
  CONSTRAINT PK_COMMUNICATION
  PRIMARY KEY (COMMUNICATIONREF, SERIALNUMBER, OWNERCODE)
)
GO
CREATE INDEX IX_COMMUNICATION_EXTERNALREF
  ON COMMUNICATION (EXTERNALREF)
GO
CREATE INDEX IX_COMMUNICATION_SUBJECT
  ON COMMUNICATION (SUBJECT)
GO
CREATE INDEX IX_COMMUNICATION_SERIALNUMBER
  ON COMMUNICATION (SERIALNUMBER)
GO
CREATE INDEX IX_COMMUNICATION_PRIORITY
  ON COMMUNICATION (PRIORITY, SERIALNUMBER, SUBJECT, CONFIDENTIAL)
GO
CREATE INDEX IX_COMMUNICATION_TYPE
  ON COMMUNICATION (COMMUNICATIONTYPE)
GO
CREATE INDEX IX_COMMUNICATION_EXREFTYPE
  ON COMMUNICATION (EXTERNALREFTYPE)
GO
CREATE INDEX IX_COMMUNICATION_DATE
  ON COMMUNICATION (DATEOFCOMMUNICATION)
GO
CREATE INDEX IX_COMMUNICATION_CREATED
  ON COMMUNICATION (CREATED)
GO
CREATE INDEX IX_COMMUNICATION_CREATEDBY
  ON COMMUNICATION (CREATEDBY)
GO
CREATE INDEX IX_COMMUNICATION_MODIFIED
  ON COMMUNICATION (MODIFIED)
GO
CREATE INDEX IX_COMMUNICATION_MODIFIEDBY
  ON COMMUNICATION (MODIFIEDBY)
GO
CREATE INDEX IX_COMMUNICATION_CONFIDENTIAL
  ON COMMUNICATION (CONFIDENTIAL)
GO
CREATE INDEX IX_COMMUNICATION_ACCESSRIGHTS
  ON COMMUNICATION (ACCESSRIGHTS)
GO
CREATE INDEX IX_COMMUNICATION_RECORDOWNER
  ON COMMUNICATION (RECORDOWNER)
GO
CREATE INDEX IX_COMMUNICATION_COMMUNICATIONREF
  ON COMMUNICATION (COMMUNICATIONREF)
GO
CREATE INDEX IX_COMMUNICATION_CRMFLAG
  ON COMMUNICATION (CRMFLAG)
GO
CREATE INDEX IX_COMMUNICATION_RESPONSE
  ON COMMUNICATION (RESPONSE)
GO
CREATE INDEX IX_COMMUNICATION_CATEGORY
  ON COMMUNICATION (CATEGORY)
GO
CREATE INDEX IX_COMMUNICATION_TIMEOFCOMMUNICATION
  ON COMMUNICATION (TIMEOFCOMMUNICATION)
GO
CREATE INDEX IX_COMMUNICATION_STICKYNOTES
  ON COMMUNICATION (SERIALNUMBER, COMMUNICATIONREF, OWNERCODE, CONFIDENTIAL, STICKY, SUBJECT, NOTES, CREATED, CREATEDBY, MODIFIED, MODIFIEDBY)
GO
