-- auto-generated definition
CREATE TABLE CONTACTPARAMETER
(
  SERIALNUMBER   VARCHAR(50)             NOT NULL,
  PARAMETERNAME  VARCHAR(100)            NOT NULL,
  PARAMETERVALUE VARCHAR(200)            NOT NULL,
  EFFECTIVEFROM  DATETIME,
  EFFECTIVETO    DATETIME,
  PARAMETERNOTE  VARCHAR(2000),
  ADDITIONAL1    VARCHAR(100) DEFAULT '' NOT NULL,
  ADDITIONAL2    VARCHAR(100) DEFAULT '' NOT NULL,
  ADDITIONAL3    VARCHAR(100) DEFAULT '' NOT NULL,
  ADDITIONAL4    VARCHAR(100),
  ADDITIONAL5    VARCHAR(1000),
  PRIORITY       VARCHAR(50),
  CREATED        DATETIME,
  CREATEDBY      VARCHAR(50),
  MODIFIED       DATETIME,
  MODIFIEDBY     VARCHAR(50),
  RECORDOWNER    VARCHAR(50),
  ID             INT IDENTITY,
  OWNERCODE      INT DEFAULT 0           NOT NULL,
  CONSTRAINT PK_CONTACTPARAMETER
  PRIMARY KEY (SERIALNUMBER, PARAMETERNAME, PARAMETERVALUE, ADDITIONAL1, ADDITIONAL2, ADDITIONAL3, OWNERCODE)
)
GO
CREATE INDEX IX_CONTACTPARAMETER_PARAMETERNAME
  ON CONTACTPARAMETER (PARAMETERNAME)
GO
CREATE INDEX IX_CONTACTPARAMETER_PARAMETERVALUE
  ON CONTACTPARAMETER (PARAMETERVALUE)
GO
CREATE INDEX IX_CONTACTPARAMETER_EFFECTIVEFROM
  ON CONTACTPARAMETER (EFFECTIVEFROM)
GO
CREATE INDEX IX_CONTACTPARAMETER_EFFECTIVETO
  ON CONTACTPARAMETER (EFFECTIVETO)
GO
CREATE INDEX IX_CONTACTPARAMETER_PRIORITY
  ON CONTACTPARAMETER (PRIORITY)
GO
CREATE INDEX IX_CONTACTPARAMETER_SERIALNUMBER
  ON CONTACTPARAMETER (SERIALNUMBER)
GO
CREATE INDEX IX_CONTACTPARAMETER_CREATED
  ON CONTACTPARAMETER (CREATED)
GO
CREATE INDEX IX_CONTACTPARAMETER_CREATEDBY
  ON CONTACTPARAMETER (CREATEDBY)
GO
CREATE INDEX IX_CONTACTPARAMETER_MODIFIED
  ON CONTACTPARAMETER (MODIFIED)
GO
CREATE INDEX IX_CONTACTPARAMETER_MODIFIEDBY
  ON CONTACTPARAMETER (MODIFIEDBY)
GO
CREATE INDEX IX_CONTACTPARAMETER_ADDITIONAL1
  ON CONTACTPARAMETER (ADDITIONAL1)
GO
CREATE INDEX IX_CONTACTPARAMETER_ADDITIONAL2
  ON CONTACTPARAMETER (ADDITIONAL2)
GO
CREATE INDEX IX_CONTACTPARAMETER_ADDITIONAL3
  ON CONTACTPARAMETER (ADDITIONAL3)
GO
CREATE INDEX IX_CONTACTPARAMETER_RECORDOWNER
  ON CONTACTPARAMETER (RECORDOWNER)
GO
CREATE UNIQUE INDEX UI_CONTACTPARAMETER_ID
  ON CONTACTPARAMETER (ID)
GO
