-- auto-generated definition
CREATE TABLE CONTACT
(
  SERIALNUMBER       VARCHAR(50)   NOT NULL,
  CONTACTTYPE        VARCHAR(15),
  TITLE              VARCHAR(30),
  FIRSTNAME          VARCHAR(50),
  OTHERINITIAL       VARCHAR(50),
  KEYNAME            VARCHAR(100),
  POSTNOMINAL        VARCHAR(20),
  ENVELOPESALUTATION VARCHAR(100),
  LETTERSALUTATION   VARCHAR(100),
  CONTACTPOSITION    VARCHAR(200),
  CAREOF             VARCHAR(100),
  ADDRESSTYPE        VARCHAR(50),
  COUNTRY            VARCHAR(50),
  POSTCODE           VARCHAR(10),
  ADDRESSLINE1       VARCHAR(255),
  ADDRESSLINE2       VARCHAR(100),
  ADDRESSLINE3       VARCHAR(100),
  ADDRESSLINE4       VARCHAR(100),
  ADDRESSLINE5       VARCHAR(100),
  ADDRESSLINE6       VARCHAR(100),
  ADDRESSCODE1       VARCHAR(50),
  ADDRESSCODE2       VARCHAR(50),
  ADDRESSCODE3       VARCHAR(50),
  SALESREGION        VARCHAR(50),
  DAYTELEPHONE       VARCHAR(30),
  EVENINGTELEPHONE   VARCHAR(30),
  FAXNUMBER          VARCHAR(30),
  MOBILENUMBER       VARCHAR(30),
  EMAILADDRESS       VARCHAR(255),
  WEBSITE            VARCHAR(150),
  CHARITYNUMBER      FLOAT,
  PRIMARYCATEGORY    VARCHAR(50),
  OCCUPATION         VARCHAR(50),
  DATEOFBIRTH        DATETIME,
  GENDER             VARCHAR(10),
  PREVIOUSNAMES      VARCHAR(255),
  MARITALSTATUS      VARCHAR(25),
  TAXSTATUS          VARCHAR(25),
  PREFERREDMETHOD    VARCHAR(10),
  DONOTMAIL          SMALLINT DEFAULT 0,
  DONOTMAILREASON    VARCHAR(50),
  DONOTMAILFROM      DATETIME,
  DONOTMAILUNTIL     DATETIME,
  SOURCE             VARCHAR(50),
  RECORDOWNER        VARCHAR(50),
  PICTUREFILE        VARCHAR(50),
  CREATED            DATETIME2,
  CREATEDBY          VARCHAR(50),
  MODIFIED           DATETIME2,
  MODIFIEDBY         VARCHAR(50),
  DEFAULTADDRESS     VARCHAR(50),
  USEADDRESSFROM     DATETIME,
  USEADDRESSUNTIL    DATETIME,
  GADSTATUS          VARCHAR(25),
  VIP                SMALLINT,
  MAINCONTACT        VARCHAR(50),
  ABN                VARCHAR(100),
  MAJORDONOR         SMALLINT,
  BEQUESTPROSPECT    SMALLINT,
  SORTKEY            VARCHAR(255),
  SORTKEYREF1        VARCHAR(50),
  SORTKEYREFREL1     VARCHAR(50),
  SORTKEYREFREL2     VARCHAR(50),
  ANONYMOUS          SMALLINT,
  RECORDVIEWTO       VARCHAR(50),
  LGA                VARCHAR(50),
  SEDUPPER           VARCHAR(50),
  SEDLOWER           VARCHAR(50),
  EMAILOK            VARCHAR(10),
  EMAILERROR         VARCHAR(255),
  CCEMAILOK          VARCHAR(10),
  CCEMAILERROR       VARCHAR(255),
  BEQUESTNOTE        VARCHAR(8000),
  WEBUSERNAME        VARCHAR(50),
  WEBPASSWORD        VARCHAR(255),
  WEBPUBLISH         SMALLINT,
  OWNERCODE          INT DEFAULT 0 NOT NULL,
  COAFLAG            INT,
  COADATE            DATETIME,
  SKYPENAME          VARCHAR(50),
  TWITTERHANDLE      VARCHAR(50),
  FACEBOOKURL        VARCHAR(255),
  LINKEDINURL        VARCHAR(255),
  CONSTRAINT PK_CONTACT
  PRIMARY KEY (SERIALNUMBER, OWNERCODE)
)
GO
CREATE INDEX IX_CONTACT_NAME
  ON CONTACT (KEYNAME, FIRSTNAME, CONTACTTYPE, RECORDVIEWTO, DONOTMAILREASON)
GO
CREATE INDEX IX_CONTACT_ADDRESS
  ON CONTACT (CONTACTTYPE, KEYNAME, FIRSTNAME, TITLE, ADDRESSLINE1, ADDRESSLINE3, ADDRESSLINE4, POSTCODE, DEFAULTADDRESS)
GO
CREATE INDEX IX_CONTACT_DEFAULTADDRESS
  ON CONTACT (DEFAULTADDRESS)
GO
CREATE INDEX IX_CONTACT_RECORDVIEWTO
  ON CONTACT (RECORDVIEWTO, SERIALNUMBER, FIRSTNAME, OTHERINITIAL, KEYNAME, OWNERCODE, ADDRESSLINE1, ABN)
GO
CREATE INDEX IX_CONTACT_KEYNAME
  ON CONTACT (KEYNAME)
GO
CREATE INDEX IX_CONTACT_EMAILADDRESS
  ON CONTACT (EMAILADDRESS)
GO
CREATE INDEX IX_CONTACT_SORTKEY
  ON CONTACT (SORTKEY)
GO
CREATE INDEX IX_CONTACT_DONOTMAIL
  ON CONTACT (DONOTMAIL)
GO
CREATE INDEX IX_CONTACT_PREFERREDMETHOD
  ON CONTACT (PREFERREDMETHOD)
GO
CREATE INDEX IX_CONTACT_USEADDRESSFROM
  ON CONTACT (USEADDRESSFROM)
GO
CREATE INDEX IX_CONTACT_USEADDRESSUNTIL
  ON CONTACT (USEADDRESSUNTIL)
GO
CREATE INDEX IX_CONTACT_ANONYMOUS
  ON CONTACT (ANONYMOUS)
GO
CREATE INDEX IX_CONTACT_SALESREGION
  ON CONTACT (SALESREGION)
GO
CREATE INDEX IX_CONTACT_DONOTMAILFROM
  ON CONTACT (DONOTMAILFROM)
GO
CREATE INDEX IX_CONTACT_DONOTMAILUNTIL
  ON CONTACT (DONOTMAILUNTIL)
GO
CREATE INDEX IX_CONTACT_VIP
  ON CONTACT (VIP)
GO
CREATE INDEX IX_CONTACT_PRIMARYCATEGORY
  ON CONTACT (PRIMARYCATEGORY)
GO
CREATE INDEX I_CONTACT_BEQUESTPROSPECT
  ON CONTACT (BEQUESTPROSPECT)
GO
CREATE INDEX IX_CONTACT_CAREOF
  ON CONTACT (CAREOF)
GO
CREATE INDEX IX_CONTACT_MOBILENUMBER
  ON CONTACT (MOBILENUMBER)
GO
CREATE INDEX IX_CONTACT_MAINCONTACT
  ON CONTACT (MAINCONTACT)
GO
CREATE INDEX I_CONTACT_MAJORDONOR
  ON CONTACT (MAJORDONOR)
GO
CREATE INDEX IX_CONTACT_EMAILOK
  ON CONTACT (EMAILOK)
GO
CREATE INDEX IX_CONTACT_CCEMAILOK
  ON CONTACT (CCEMAILOK)
GO
CREATE INDEX IX_CONTACT_WEBUSER
  ON CONTACT (WEBUSERNAME, SERIALNUMBER, OWNERCODE)
GO
CREATE INDEX IX_CONTACT_WEBUSERPUBLISH
  ON CONTACT (WEBUSERNAME, WEBPUBLISH, SERIALNUMBER)
GO
DECLARE @sn NVARCHAR(30)
SET @sn = schema_name()
EXECUTE sp_addextendedproperty N'MS_Description', N'Any notes relating to a beques', N'SCHEMA', @sn, N'TABLE', N'CONTACT', N'COLUMN', N'BEQUESTNOTE'
GO
