-- auto-generated definition
CREATE TABLE DESTINATIONCODE
(
  DESTINATIONCODE           VARCHAR(25)   NOT NULL,
  DESTINATIONTYPE           VARCHAR(50),
  DESTINATIONDESCRIPTION    VARCHAR(255),
  DESTINATIONNOTES          VARCHAR(1000),
  LEDGERCODE                VARCHAR(50),
  RECORDOWNER               VARCHAR(25),
  MODIFIED                  DATETIME,
  MODIFIEDBY                VARCHAR(50),
  CREATED                   DATETIME,
  CREATEDBY                 VARCHAR(50),
  EXCLUDEFROMDROPDOWN       SMALLINT DEFAULT 0,
  ARCHIVE                   FLOAT    DEFAULT 0,
  AVAILONTIMESHEET          SMALLINT,
  ADDITIONALCODE1           VARCHAR(255),
  ADDITIONALCODE2           VARCHAR(50),
  ADDITIONALCODE3           VARCHAR(255),
  ADDITIONALCODE4           VARCHAR(50),
  ADDITIONALCODE5           VARCHAR(50),
  RECEIPTSPLITORDER         INT,
  REPORTFINANCESYSTEMDETAIL SMALLINT,
  ACCOUNTNAME               VARCHAR(50),
  SORTCODE                  VARCHAR(50),
  ACCOUNTNUMBER             VARCHAR(20),
  BANKNAME                  VARCHAR(100),
  BANKADDRESS               VARCHAR(255),
  BANKPOSTCODE              VARCHAR(10),
  OWNERCODE                 INT DEFAULT 0 NOT NULL,
  GATEWAYNAME               VARCHAR(50),
  NONALLOCABLE              SMALLINT,
  CONSTRAINT PK_DESTINATIONCODE
  PRIMARY KEY (DESTINATIONCODE, OWNERCODE)
)
GO
CREATE INDEX I_DESTCODE_DESTINATIONTYPE
  ON DESTINATIONCODE (DESTINATIONTYPE)
GO
CREATE INDEX I_DESTCODE_DESTINATIONDESCRIPTION
  ON DESTINATIONCODE (DESTINATIONDESCRIPTION)
GO
CREATE INDEX I_DESTCODE_AVAILONTIMESHEET
  ON DESTINATIONCODE (AVAILONTIMESHEET)
GO
CREATE INDEX I_DESTCODE_LEDGERCODE
  ON DESTINATIONCODE (LEDGERCODE)
GO
CREATE INDEX I_DESTCODE_RECORDOWNER
  ON DESTINATIONCODE (RECORDOWNER)
GO
CREATE INDEX I_DESTCODE_EXCLUDEFROMDROPDOWN
  ON DESTINATIONCODE (EXCLUDEFROMDROPDOWN)
GO
CREATE INDEX I_DESTCODE_ARCHIVE
  ON DESTINATIONCODE (ARCHIVE)
GO
CREATE INDEX IX_DESTINATIONCODE_ADDITIONALCODE1
  ON DESTINATIONCODE (ADDITIONALCODE1)
GO
CREATE INDEX IX_DESTINATIONCODE_ADDITIONALCODE2
  ON DESTINATIONCODE (ADDITIONALCODE2)
GO
CREATE INDEX IX_DESTINATIONCODE_ADDTIONALCODE3
  ON DESTINATIONCODE (ADDITIONALCODE3)
GO
CREATE INDEX IX_DESTINATIONCODE_ADDITIONALCODE4
  ON DESTINATIONCODE (ADDITIONALCODE4)
GO
CREATE INDEX IX_DESTINATIONCODE_ADDITIONALCODE5
  ON DESTINATIONCODE (ADDITIONALCODE5)
GO
CREATE INDEX I_DESTCODE_RECEIPTSPLITORDER
  ON DESTINATIONCODE (RECEIPTSPLITORDER)
GO
CREATE INDEX IX_DESTINATIONCODE_REPORTFINSYSDETAIL
  ON DESTINATIONCODE (REPORTFINANCESYSTEMDETAIL)
GO
CREATE INDEX I_DESTCODE_NONALLOCABLE
  ON DESTINATIONCODE (NONALLOCABLE)
GO
