-- auto-generated definition
CREATE TABLE PLEDGEINSTALMENTS_NEXTACTIVE
(
  PLEDGEID     VARCHAR(150) NOT NULL
    CONSTRAINT PK_PLEDGEINSTALMENTS_NEXTACTIVE
    PRIMARY KEY,
  INSTALMENTID FLOAT        NOT NULL,
  INSTALMENT   MONEY,
  DATEDUE      DATETIME,
  AMOUNTPAID   MONEY DEFAULT 0
)
GO
CREATE INDEX I_PLEDGE_NEXTACTIVE_INSTID
  ON PLEDGEINSTALMENTS_NEXTACTIVE (INSTALMENTID)
GO
CREATE INDEX I_PLEDGE_NEXTACTIVE_INSTALMENT
  ON PLEDGEINSTALMENTS_NEXTACTIVE (INSTALMENT)
GO
CREATE INDEX I_PLEDGE_NEXTACTIVE_DATEDUE
  ON PLEDGEINSTALMENTS_NEXTACTIVE (DATEDUE)
GO
CREATE INDEX I_PLEDGE_NEXTACTIVE_AMOUNTPAID
  ON PLEDGEINSTALMENTS_NEXTACTIVE (AMOUNTPAID)
GO
