-- auto-generated definition
CREATE TABLE PLEDGEREACTIVATION
(
  OWNERCODE         INT DEFAULT 0 NOT NULL,
  REACTIVATIONID    VARCHAR(50)   NOT NULL,
  SERIALNUMBER      VARCHAR(50),
  PLEDGEID          VARCHAR(50),
  REACTIVATIONDATE  DATETIME,
  LASTUPDATE        DATETIME,
  REACTIVATIONSTAGE VARCHAR(50) DEFAULT 'Round 1',
  REACTIVATIONTYPE  VARCHAR(50),
  COMMENT           VARCHAR(8000),
  CREATED           DATETIME,
  CREATEDBY         VARCHAR(50),
  MODIFIED          DATETIME,
  MODIFIEDBY        VARCHAR(50),
  ARCHIVE           SMALLINT    DEFAULT 0,
  COMMUNICATIONREF  VARCHAR(50),
  CONSTRAINT PK_PLEDGEREACTIVATION
  PRIMARY KEY (OWNERCODE, REACTIVATIONID)
)
GO
CREATE INDEX IX_PLEDGEREACTIVATION_SERIALNUMBER
  ON PLEDGEREACTIVATION (SERIALNUMBER)
GO
