-- auto-generated definition
CREATE TABLE PLEDGEINSTALMENTS_WRITTENOFF
(
  PLEDGEID           VARCHAR(150) NOT NULL,
  INSTALMENTID       FLOAT        NOT NULL,
  INSTALMENT         MONEY,
  DATEDUE            DATETIME,
  AMOUNTPAID         MONEY DEFAULT 0,
  ORIGINALINSTALMENT MONEY,
  CAMPAIGNYEAR       INT   DEFAULT 0,
  COMMENTS           VARCHAR(3000),
  INVOICENTH         NUMERIC(18),
  WRITTENDOWN        DATETIME,
  WRITTENDOWNBY      VARCHAR(50),
  WRITTENDOWNREASON  VARCHAR(100),
  CONSTRAINT PK_PLEDGEINSTALMENTS_WRITTENOFF
  PRIMARY KEY (PLEDGEID, INSTALMENTID)
)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_DUE
  ON PLEDGEINSTALMENTS_WRITTENOFF (DATEDUE)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_INS
  ON PLEDGEINSTALMENTS_WRITTENOFF (INSTALMENT)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_PAID
  ON PLEDGEINSTALMENTS_WRITTENOFF (AMOUNTPAID)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_ORIGINSTAL
  ON PLEDGEINSTALMENTS_WRITTENOFF (ORIGINALINSTALMENT)
GO
CREATE INDEX I_PLEDGE_WRITTENOFF_YEAR
  ON PLEDGEINSTALMENTS_WRITTENOFF (CAMPAIGNYEAR)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_WRITTENOFF_INVOICENTH
  ON PLEDGEINSTALMENTS_WRITTENOFF (INVOICENTH)
GO
