-- auto-generated definition
CREATE TABLE PLEDGEINSTALMENTS_ACTIVE
(
  PLEDGEID     VARCHAR(150) NOT NULL,
  INSTALMENTID FLOAT        NOT NULL,
  INSTALMENT   MONEY,
  DATEDUE      DATETIME,
  AMOUNTPAID   MONEY DEFAULT 0,
  ONHOLD       SMALLINT,
  CAMPAIGNYEAR INT   DEFAULT 0,
  COMMENTS     VARCHAR(3000),
  INVOICENTH   NUMERIC(18),
  CONSTRAINT PK_PLEDGEINSTALMENTS_ACTIVE
  PRIMARY KEY (PLEDGEID, INSTALMENTID)
)
GO
CREATE INDEX I_PLEDGEINSTALMENTS_ACTIVE_DAT
  ON PLEDGEINSTALMENTS_ACTIVE (DATEDUE)
GO
CREATE INDEX I_PLEDGEINSTALMENTS_ACTIVE_INS
  ON PLEDGEINSTALMENTS_ACTIVE (INSTALMENT)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_ACTIVE_PAID
  ON PLEDGEINSTALMENTS_ACTIVE (AMOUNTPAID)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_ACTIVE_ON
  ON PLEDGEINSTALMENTS_ACTIVE (ONHOLD)
GO
CREATE INDEX I_PLEDGEINST_ACTIVE_YEAR
  ON PLEDGEINSTALMENTS_ACTIVE (CAMPAIGNYEAR)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_ACTIVE_INVOICENTH
  ON PLEDGEINSTALMENTS_ACTIVE (INVOICENTH)
GO
