-- auto-generated definition
CREATE TABLE PLEDGEHEADERRELATIONSHIP
(
  PLEDGEID     VARCHAR(150) NOT NULL,
  SERIALNUMBER VARCHAR(50)  NOT NULL,
  DESIGNATION  VARCHAR(10),
  CONSTRAINT PK_PLEDGEHEADERRELATIONSHIP
  PRIMARY KEY (PLEDGEID, SERIALNUMBER)
)
GO
CREATE INDEX IX_PLEDGEHEADERRELATIONSHIP
  ON PLEDGEHEADERRELATIONSHIP (DESIGNATION)
GO
CREATE INDEX IX_PLEDGEHEADERREL_PLEDGEID
  ON PLEDGEHEADERRELATIONSHIP (PLEDGEID)
GO
CREATE INDEX IX_PLEDGEHEADERREL_SERIALNUMBER
  ON PLEDGEHEADERRELATIONSHIP (SERIALNUMBER)
GO
