-- auto-generated definition
CREATE TABLE PLEDGEHEADER
(
  PLEDGEID               VARCHAR(150)  NOT NULL,
  PLEDGESTATUS           VARCHAR(25),
  SERIALNUMBER           VARCHAR(50)   NOT NULL,
  DESCRIPTION            VARCHAR(255),
  PLEDGEPLAN             VARCHAR(50),
  PLEDGETYPE             VARCHAR(25),
  CURRENCY               VARCHAR(25),
  SOURCECODE             VARCHAR(25),
  SOURCECODE2            VARCHAR(25),
  CAMPAIGNYEAR           INT,
  PAYMENTTYPE            VARCHAR(25),
  RECEIPTREQUIRED        VARCHAR(4),
  RECEIPTSUMMARY         VARCHAR(4),
  RECEIPTFREQUENCY       VARCHAR(25),
  NEXTRECEIPTDATE        DATETIME,
  STARTDATE              DATETIME,
  ENDDATE                DATETIME,
  TOTALVALUE             MONEY,
  INSTALMENTVALUE        MONEY,
  PAYMENTFREQUENCY       VARCHAR(25),
  MAXPAYMENTS            INT,
  ACCOUNTNAME            VARCHAR(50),
  SORTCODE               VARCHAR(10),
  ACCOUNTNUMBER          VARCHAR(20),
  ROLLNUMBER             VARCHAR(20),
  TEXT1                  VARCHAR(255),
  TEXT2                  VARCHAR(255),
  BANKNAME               VARCHAR(100),
  BANKADDRESS            VARCHAR(255),
  BANKPOSTCODE           VARCHAR(10),
  CREDITCARDTYPE         VARCHAR(20),
  CREDITCARDNUMBER       VARCHAR(100),
  CREDITCARDHOLDER       VARCHAR(100),
  CREDITCARDEXPIRY       VARCHAR(8),
  CREDITCARDISSUENUMBER  VARCHAR(5),
  CREDITCARDMETHOD       VARCHAR(50),
  PLEDGERECRUITEDBY      VARCHAR(255),
  PLEDGERECRUITEDBYEVENT VARCHAR(25),
  RECORDOWNER            VARCHAR(25),
  CREATED                DATETIME,
  CREATEDBY              VARCHAR(50),
  MODIFIED               DATETIME,
  MODIFIEDBY             VARCHAR(50),
  TAXCLAIMABLE           VARCHAR(4),
  EXTERNALREF            VARCHAR(25),
  EXTERNALREFTYPE        VARCHAR(25),
  ESCALATIONLETTER       SMALLINT DEFAULT 0,
  LASTESCALATIONDATE     DATETIME,
  MEMBERSHIP             SMALLINT,
  MEMBERSHIPID           VARCHAR(50),
  SUBSCRIPTION           SMALLINT,
  SUBSCRIPTIONID         VARCHAR(50),
  NEW                    SMALLINT,
  EXISTING               SMALLINT,
  RECOVERED              SMALLINT,
  ACKNOWLEDGE            VARCHAR(4),
  ACKNOWLEDGEDATE        DATETIME,
  ACKNOWLEDGELETTER      VARCHAR(50),
  TOTALPAID              MONEY    DEFAULT 0,
  OUTSTANDING            MONEY    DEFAULT 0,
  ORIGINALTOTALVALUE     MONEY    DEFAULT 0,
  ONEOFF                 VARCHAR(4),
  TITLE                  VARCHAR(30),
  FIRSTNAME              VARCHAR(50),
  KEYNAME                VARCHAR(100),
  WRITTENDOWNREASON      VARCHAR(100),
  WRITTENDOWN            DATETIME,
  WRITTENDOWNBY          VARCHAR(50),
  ONHOLDREASON           VARCHAR(100),
  ONHOLDDATETIME         DATETIME,
  ONHOLDBY               VARCHAR(50),
  REMINDER               VARCHAR(3),
  CREDITCARDTOKEN        VARCHAR(50),
  CREDITCARDMASKED       VARCHAR(100),
  OWNERCODE              INT DEFAULT 0 NOT NULL,
  TOKENGATEWAY           VARCHAR(50),
  ONREACTIVATIONLIST     VARCHAR(50),
  REACTIVATIONFOLLOWUP   DATETIME,
  PLEDGERECRUITEDBYDATE  DATETIME,
  RECRUITERID            VARCHAR(20),
  FUNDRAISERID           VARCHAR(20),
  RECRUITMENTAGENCYID    VARCHAR(20),
  RECRUITMENTMETHOD      VARCHAR(50),
  RECRUITMENTLOCATION    VARCHAR(100),
  NEXTCALLDATE           DATETIME,
  CALLOUTCOME            VARCHAR(50),
  CALLDETAIL             VARCHAR(2000),
  CURRENTYEARVALUE       MONEY,
  CONSTRAINT PK_PLEDGEHEADER
  PRIMARY KEY (PLEDGEID, OWNERCODE)
)
GO
CREATE INDEX I_PLEDGEHEADER_PLEDGEID
  ON PLEDGEHEADER (PLEDGEID)
GO
CREATE UNIQUE INDEX UI_PLEDGEHEADER
  ON PLEDGEHEADER (SERIALNUMBER, PLEDGEID)
GO
CREATE INDEX I_PLEDGEHEADER_SORTCODE
  ON PLEDGEHEADER (SORTCODE)
GO
CREATE INDEX IX_PLEDGEHEADER_STARTDATE
  ON PLEDGEHEADER (STARTDATE)
GO
CREATE INDEX IX_PLEDGEHEADER_EXTERNALREF
  ON PLEDGEHEADER (EXTERNALREF)
GO
CREATE INDEX IX_PLEDGEHEADER_ONHOLDREASON
  ON PLEDGEHEADER (ONHOLDREASON)
GO
CREATE INDEX IX_PLEDGEHEADER_PLEDGEPLAN
  ON PLEDGEHEADER (PLEDGEPLAN)
GO
CREATE INDEX IX_PLEDGEHEADER_RECEIPTREQUIRED
  ON PLEDGEHEADER (RECEIPTREQUIRED)
GO
CREATE INDEX IX_PLEDGEHEADER_CREDITCARDHOLDER
  ON PLEDGEHEADER (CREDITCARDHOLDER)
GO
CREATE INDEX IX_PLEDGEHEADER_FIRSTNAME
  ON PLEDGEHEADER (FIRSTNAME)
GO
CREATE INDEX IX_PLEDGEHEADER_KEYNAME
  ON PLEDGEHEADER (KEYNAME)
GO
CREATE INDEX IX_PLEDGEHEADER_SERIALNUMBER
  ON PLEDGEHEADER (SERIALNUMBER)
GO
CREATE INDEX IX_PLEDGEHEADER_EXISTING
  ON PLEDGEHEADER (EXISTING)
GO
CREATE INDEX IX_PLEDGEHEADER_RECOVERED
  ON PLEDGEHEADER (RECOVERED)
GO
CREATE INDEX IX_PLEDGEHEADER_RECEIPTSUMMARY
  ON PLEDGEHEADER (RECEIPTSUMMARY)
GO
CREATE INDEX IX_PLEDGEHEADER_CREDITCARDTYPE
  ON PLEDGEHEADER (CREDITCARDTYPE)
GO
CREATE INDEX IX_PLEDGEHEADER_ONHOLDDATETIME
  ON PLEDGEHEADER (ONHOLDDATETIME)
GO
CREATE INDEX IX_PLEDGEHEADER_TOTALPAID
  ON PLEDGEHEADER (TOTALPAID)
GO
CREATE INDEX IX_PLEDGEHEADER_OUTSTANDING
  ON PLEDGEHEADER (OUTSTANDING)
GO
CREATE INDEX IX_PLEDGEHEADER_PLEDGESTATUS
  ON PLEDGEHEADER (PLEDGESTATUS, EXTERNALREFTYPE, PLEDGEID, SERIALNUMBER, TOTALVALUE)
GO
CREATE INDEX IX_PLEDGEHEADER_PLEDGETYPE
  ON PLEDGEHEADER (PLEDGETYPE)
GO
CREATE INDEX IX_PLEDGEHEADER_PAYMENTTYPE
  ON PLEDGEHEADER (PAYMENTTYPE)
GO
CREATE INDEX IX_PLEDGEHEADER_EXTERNALREFTYPE
  ON PLEDGEHEADER (EXTERNALREFTYPE)
GO
CREATE INDEX IX_PLEDGEHEADER_WRITTENDOWNREASON
  ON PLEDGEHEADER (WRITTENDOWNREASON)
GO
CREATE INDEX IX_PLEDGEHEADER_WRITTENDOWN
  ON PLEDGEHEADER (WRITTENDOWN)
GO
CREATE INDEX IX_PLEDGEHEADER_ONHOLDBY
  ON PLEDGEHEADER (ONHOLDBY)
GO
CREATE INDEX IX_PLEDGEHEADER_DESCRIPTION
  ON PLEDGEHEADER (DESCRIPTION)
GO
CREATE INDEX IX_PLEDGEHEADER_REMINDER
  ON PLEDGEHEADER (REMINDER)
GO
CREATE INDEX IX_PLEDGEHEADER_PLEDGERECRUITEDBYDATE
  ON PLEDGEHEADER (PLEDGERECRUITEDBYDATE)
GO
