-- auto-generated definition
CREATE TABLE PLEDGEINSTALMENTS_CLOSED
(
  PLEDGEID     VARCHAR(150) NOT NULL,
  INSTALMENTID FLOAT        NOT NULL,
  INSTALMENT   MONEY,
  DATEDUE      DATETIME,
  AMOUNTPAID   MONEY DEFAULT 0,
  CAMPAIGNYEAR INT   DEFAULT 0,
  COMMENTS     VARCHAR(3000),
  INVOICENTH   NUMERIC(18),
  CONSTRAINT PK_PLEDGEINSTALMENTS_CLOSED
  PRIMARY KEY (PLEDGEID, INSTALMENTID)
)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_DUE
  ON PLEDGEINSTALMENTS_CLOSED (DATEDUE)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_INS
  ON PLEDGEINSTALMENTS_CLOSED (INSTALMENT)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_PAID
  ON PLEDGEINSTALMENTS_CLOSED (AMOUNTPAID)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_YEAR
  ON PLEDGEINSTALMENTS_CLOSED (CAMPAIGNYEAR)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_CLOSED_INVOICENTH
  ON PLEDGEINSTALMENTS_CLOSED (INVOICENTH)
GO
