-- auto-generated definition
CREATE TABLE PLEDGEHEADERATTRIBUTE
(
  PLEDGEID         VARCHAR(150) NOT NULL
    CONSTRAINT PK_PLEDGEHEADERATTRIBUTE
    PRIMARY KEY NONCLUSTERED,
  DESTINATIONCODE  VARCHAR(50),
  DESTINATIONCODE2 VARCHAR(50),
  PAYMENTRATIO     MONEY,
  NOTES            VARCHAR(MAX),
  AUDITNOTES       VARCHAR(8000),
  CREDITCARDMASKED VARCHAR(100)
)
GO
CREATE INDEX I_PLEDGEHEADERATTRIBUTE_PLEDGE
  ON PLEDGEHEADERATTRIBUTE (PLEDGEID)
GO
CREATE UNIQUE INDEX UI_PLEDGEHEADERATTRIBUTE
  ON PLEDGEHEADERATTRIBUTE (PLEDGEID)
GO
CREATE INDEX IX_PLEDGEHEADERATTR_DESTCODE
  ON PLEDGEHEADERATTRIBUTE (DESTINATIONCODE)
GO
CREATE INDEX IX_PLEDGEHEADERATTR_DESTCODE2
  ON PLEDGEHEADERATTRIBUTE (DESTINATIONCODE2)
GO
CREATE INDEX IX_PLEDGEHEADERATTR_PAYMENTRATIO
  ON PLEDGEHEADERATTRIBUTE (PAYMENTRATIO)
GO
