-- auto-generated definition
CREATE TABLE PLEDGEINSTALMENTS_FAILURE
(
  ID             INT IDENTITY
    CONSTRAINT PK_PLEDGEINSTALMENTS_FAILURE
    PRIMARY KEY,
  PLEDGEID       VARCHAR(150),
  INSTALMENTID   FLOAT,
  BATCHID        VARCHAR(50),
  RECEIPTNO      VARCHAR(150),
  DATEOFPAYMENT  DATETIME,
  RESULT         VARCHAR(255),
  CREATED        DATETIME,
  CREATEDBY      VARCHAR(50),
  MODIFIED       DATETIME,
  MODIFIEDBY     VARCHAR(50),
  AUTOMATIONFLAG INT
)
GO
CREATE INDEX IX_PLEDGEINSTALMENTS_FAILURE
  ON PLEDGEINSTALMENTS_FAILURE (PLEDGEID)
GO
