-- auto-generated definition
CREATE TABLE PLEDGEDESTINATION
(
  PLEDGEID         VARCHAR(150) NOT NULL,
  AUTOID           NUMERIC(18)  NOT NULL,
  SOURCECODE       VARCHAR(50),
  SOURCECODE2      VARCHAR(50),
  DESTINATIONCODE  VARCHAR(50),
  DESTINATIONCODE2 VARCHAR(50),
  CAMPAIGNYEAR     INT,
  PAYMENTRATIO     MONEY DEFAULT 0,
  CONSTRAINT PK_PLEDGEDESTINATION
  PRIMARY KEY (PLEDGEID, AUTOID)
)
GO
CREATE INDEX IX_PLEDGEDESTINATION_SOURCECODE2
  ON PLEDGEDESTINATION (SOURCECODE2, PLEDGEID, PAYMENTRATIO)
GO
CREATE INDEX IX_PLEDGEDEST_DESTINATIONCODE
  ON PLEDGEDESTINATION (DESTINATIONCODE)
GO
CREATE INDEX IX_PLEDGEDEST_DESTINATIONCODE2
  ON PLEDGEDESTINATION (DESTINATIONCODE2)
GO
CREATE INDEX IX_PLEDGEDESTINATION_SOURCECODE
  ON PLEDGEDESTINATION (SOURCECODE, PLEDGEID, PAYMENTRATIO)
GO
CREATE INDEX IX_PLEDGEDESTINATION_CAMPAIGNYEAR
  ON PLEDGEDESTINATION (CAMPAIGNYEAR)
GO
