-- auto-generated definition
CREATE TABLE SOURCECODE
(
  SOURCECODE            VARCHAR(25)   NOT NULL,
  SOURCETYPE            VARCHAR(50),
  SOURCEDESCRIPTION     VARCHAR(255),
  SOURCENOTES           VARCHAR(1000),
  SOURCESTARTDATE       DATETIME,
  SOURCEENDDATE         DATETIME,
  RECORDOWNER           VARCHAR(50),
  CREATED               DATETIME,
  CREATEDBY             VARCHAR(50),
  MODIFIED              DATETIME,
  MODIFIEDBY            VARCHAR(50),
  EXCLUDEFROMDROPDOWN   SMALLINT     DEFAULT 0,
  ARCHIVE               SMALLINT     DEFAULT 0,
  SOURCETARGET          MONEY,
  SOURCEBUDGET          MONEY,
  DESTINATIONCODE       VARCHAR(25),
  DESTINATIONCODE2      VARCHAR(25),
  TAXDEDUCTIBLE         SMALLINT,
  GOODSTAXAPPLICABLE    SMALLINT     DEFAULT 0,
  EXCLUDEFROMSTATISTICS SMALLINT,
  ADDITIONALCODE1       VARCHAR(50),
  ADDITIONALCODE2       VARCHAR(50),
  ADDITIONALCODE3       VARCHAR(50),
  ADDITIONALCODE4       VARCHAR(50),
  ADDITIONALCODE5       VARCHAR(50),
  AVAILONTIMESHEET      SMALLINT,
  SEPARATERECEIPTS      VARCHAR(50),
  LOTTERYFLAG           SMALLINT,
  SOURCECODE2           VARCHAR(50),
  ACCOUNTNAME           VARCHAR(50),
  SORTCODE              VARCHAR(50),
  ACCOUNTNUMBER         VARCHAR(20),
  BANKNAME              VARCHAR(100),
  BANKADDRESS           VARCHAR(255),
  BANKPOSTCODE          VARCHAR(10),
  OWNERCODE             INT DEFAULT 0 NOT NULL,
  EDHEVENT              VARCHAR(255),
  INPUTTAXED            SMALLINT,
  CATEGORY              VARCHAR(50),
  NETREPORTING          SMALLINT,
  AUDITNOTE             VARCHAR(MAX) DEFAULT '',
  CONSTRAINT PK_SOURCECODE
  PRIMARY KEY (SOURCECODE, OWNERCODE)
)
GO
CREATE INDEX IX_SOURCECODE_SOURCETYPE
  ON SOURCECODE (SOURCETYPE)
GO
CREATE INDEX IX_SOURCECODE_STARTDATE
  ON SOURCECODE (SOURCESTARTDATE)
GO
CREATE INDEX IX_SOURCECODE_ENDDATE
  ON SOURCECODE (SOURCEENDDATE)
GO
CREATE INDEX IX_SOURCECODE_EXCLDROPDOWN
  ON SOURCECODE (EXCLUDEFROMDROPDOWN)
GO
CREATE INDEX IX_SOURCECODE_ARCHIVE
  ON SOURCECODE (ARCHIVE)
GO
CREATE INDEX IX_SOURCECODE_SOURCETARGET
  ON SOURCECODE (SOURCETARGET)
GO
CREATE INDEX IX_SOURCECODE_SOURCEBUDGET
  ON SOURCECODE (SOURCEBUDGET)
GO
CREATE INDEX IX_SOURCECODE_DESTINATIONCODE
  ON SOURCECODE (DESTINATIONCODE)
GO
CREATE INDEX IX_SOURCECODE_TAXDEDUCTIBLE
  ON SOURCECODE (TAXDEDUCTIBLE)
GO
CREATE INDEX IX_SOURCECODE_GOODSTAXAPPL
  ON SOURCECODE (GOODSTAXAPPLICABLE)
GO
CREATE INDEX IX_SOURCECODE_EXCLUDEFROMSTATS
  ON SOURCECODE (EXCLUDEFROMSTATISTICS)
GO
CREATE INDEX IX_SOURCECODE_DESTINATIONCODE2
  ON SOURCECODE (DESTINATIONCODE2)
GO
CREATE INDEX IX_SOURCECODE_ADDITIONALCODE1
  ON SOURCECODE (ADDITIONALCODE1)
GO
CREATE INDEX IX_SOURCECODE_ADDITIONALCODE2
  ON SOURCECODE (ADDITIONALCODE2)
GO
CREATE INDEX IX_SOURCECODE_ADDITIONALCODE3
  ON SOURCECODE (ADDITIONALCODE3)
GO
CREATE INDEX IX_SOURCECODE_ADDITIONALCODE4
  ON SOURCECODE (ADDITIONALCODE4)
GO
CREATE INDEX IX_SOURCECODE_ADDITIONALCODE5
  ON SOURCECODE (ADDITIONALCODE5)
GO
CREATE INDEX IX_SOURCECODE_AVAILONTIMESHEET
  ON SOURCECODE (AVAILONTIMESHEET)
GO
CREATE INDEX IX_SOURCECODE_SEPARATERECEIPTS
  ON SOURCECODE (SEPARATERECEIPTS)
GO
CREATE INDEX IX_SOURCECODE_LOTTERYFLAG
  ON SOURCECODE (LOTTERYFLAG)
GO
CREATE INDEX IX_SOURCECODE_SOURCECODE2
  ON SOURCECODE (SOURCECODE2)
GO
CREATE INDEX IX_SOURCECODE_EDHEVENT
  ON SOURCECODE (EDHEVENT)
GO
CREATE INDEX IX_SOURCECODE_INPUTTAXED
  ON SOURCECODE (INPUTTAXED)
GO
CREATE INDEX IX_SOURCECODE_EXCLUDEARCHIVELOTTERY
  ON SOURCECODE (EXCLUDEFROMDROPDOWN, ARCHIVE, LOTTERYFLAG, SOURCECODE)
GO
