-- auto-generated definition
CREATE TABLE SOURCECODE2
(
  SOURCECODE2          VARCHAR(50)   NOT NULL,
  SERIALNUMBER         VARCHAR(50),
  CATEGORY             VARCHAR(50),
  TYPE                 VARCHAR(50),
  DESCRIPTION          VARCHAR(255),
  NOTES                VARCHAR(2500),
  EXCLUDEFROMDROPDOWN  SMALLINT,
  ARCHIVE              SMALLINT,
  CREATED              DATETIME,
  CREATEDBY            VARCHAR(50),
  MODIFIED             DATETIME,
  MODIFIEDBY           VARCHAR(50),
  PREFIX               VARCHAR(50),
  LOWERMANUALRECEIPTNO INT,
  UPPERMANUALRECEIPTNO INT,
  OWNERCODE            INT DEFAULT 0 NOT NULL,
  TARGET               MONEY,
  CONSTRAINT PK_SOURCECODE2
  PRIMARY KEY (SOURCECODE2, OWNERCODE)
)
GO
CREATE INDEX IX_SOURCECODE2_ARCHIVE
  ON SOURCECODE2 (ARCHIVE)
GO
CREATE INDEX IX_SOURCECODE2_CATEGORY
  ON SOURCECODE2 (CATEGORY)
GO
CREATE INDEX IX_SOURCECODE2_CREATED
  ON SOURCECODE2 (CREATED)
GO
CREATE INDEX IX_SOURCECODE2_CREATEDBY
  ON SOURCECODE2 (CREATEDBY)
GO
CREATE INDEX IX_SOURCECODE2_DESCRIPTION
  ON SOURCECODE2 (DESCRIPTION)
GO
CREATE INDEX IX_SOURCECODE2_EXCLUDEFROMDROPDOWN
  ON SOURCECODE2 (EXCLUDEFROMDROPDOWN)
GO
CREATE INDEX IX_SOURCECODE2_MODIFIED
  ON SOURCECODE2 (MODIFIED)
GO
CREATE INDEX IX_SOURCECODE2_MODIFIEDBY
  ON SOURCECODE2 (MODIFIEDBY)
GO
CREATE INDEX IX_SOURCECODE2_TYPE
  ON SOURCECODE2 (TYPE)
GO
CREATE INDEX IX_SOURCECODE2_SERIALNUMBER
  ON SOURCECODE2 (SERIALNUMBER)
GO
CREATE INDEX IX_SOURCECODE2_LOWERMANUALRECEIPTNO
  ON SOURCECODE2 (LOWERMANUALRECEIPTNO)
GO
CREATE INDEX IX_SOURCECODE2_UPPERMANUALRECEIPTNO
  ON SOURCECODE2 (UPPERMANUALRECEIPTNO)
GO
CREATE INDEX IX_SOURCECODE2_PREFIX
  ON SOURCECODE2 (PREFIX)
GO
