WITH cte_legit_pledge as (
  SELECT PLEDGEID
    ,CHK_STARTDATE = IIF(STARTDATE IS NULL,':BLANK',CONCAT(CAST(YEAR(STARTDATE) AS VARCHAR(4)),'.',CAST(MONTH(STARTDATE) AS VARCHAR(2))))
    ,STARTDATE,ENDDATE
    ,DESCRIPTION = IIF(DESCRIPTION IS NULL OR RTRIM(DESCRIPTION)='',':BLANK', DESCRIPTION)
    ,PLEDGERECRUITEDBY = IIF(PLEDGERECRUITEDBY IS NULL OR RTRIM(PLEDGERECRUITEDBY)='',':BLANK', PLEDGERECRUITEDBY)
    ,PLEDGESTATUS = IIF(PLEDGESTATUS IS NULL OR RTRIM(PLEDGESTATUS)='',':BLANK', PLEDGESTATUS)
    ,PLEDGEPLAN = IIF(PLEDGEPLAN IS NULL OR RTRIM(PLEDGEPLAN)='',':BLANK', PLEDGEPLAN)
    ,PLEDGETYPE = IIF(PLEDGETYPE IS NULL OR RTRIM(PLEDGETYPE)='',':BLANK', PLEDGETYPE)
    ,PAYMENTFREQUENCY = IIF(PAYMENTFREQUENCY IS NULL OR RTRIM(PAYMENTFREQUENCY)='',':BLANK', PAYMENTFREQUENCY)
    ,INSTALMENTVALUE = IIF(INSTALMENTVALUE IS NULL OR INSTALMENTVALUE=0, 0, INSTALMENTVALUE)
    ,PAYMENTTYPE = IIF(PAYMENTTYPE IS NULL OR RTRIM(PAYMENTTYPE)='',':BLANK', PAYMENTTYPE)
    ,CREATED
    ,CREATEDBY= IIF(CREATEDBY IS NULL OR RTRIM(CREATEDBY)='',':BLANK', CREATEDBY)
    ,EXTERNALREFTYPE = IIF(EXTERNALREFTYPE IS NULL OR RTRIM(EXTERNALREFTYPE)='',':BLANK', EXTERNALREFTYPE)
    ,EXTERNALREF = IIF(EXTERNALREF IS NULL OR RTRIM(EXTERNALREF)='',':BLANK', EXTERNALREFTYPE)
  FROM TBL_PLEDGEHEADER P1
  WHERE 
    (EXTERNALREF IS NULL OR RTRIM(EXTERNALREF)='') AND (EXTERNALREFTYPE IS NULL OR RTRIM(EXTERNALREFTYPE)='')
    AND (DESCRIPTION IS NULL OR DESCRIPTION NOT LIKE '%MERCH%' OR DESCRIPTION NOT LIKE '%LEGACY%')
    AND CREATED >= DATEFROMPARTS(/*<START_YEAR>*/YEAR(GETDATE())-1/*</START_YEAR>*/,/*<START_MTH>*/MONTH(GETDATE())/*</START_MTH>*/,/*<START_DAY>*/1/*</START_DAY>*/)
    AND CREATED <= DATEADD(day,1,DATEFROMPARTS(/*<END_YEAR>*/YEAR(GETDATE())/*</END_YEAR>*/,/*<END_MTH>*/MONTH(GETDATE())/*</END_MTH>*/,/*<END_DAY>*/DAY(GETDATE())/*</END_DAY>*/+1))
)
-- --------------------------------------------------------------
,cte_pledge_source as (
  SELECT PLEDGEID
  ,CNT_SOURCECODE=COUNT(SOURCECODE),CNT_SOURCECODE2=COUNT(SOURCECODE2),CNT_DESTINATIONCODE=COUNT(DESTINATIONCODE),CNT_DESTINATIONCODE2=COUNT(DESTINATIONCODE2)
  ,CHK_SOURCECODE=IIF(COUNT(SOURCECODE)=0,':BLANK',IIF(COUNT(SOURCECODE)=1,'Only One','Multiple'))
  ,FIRST_SOURCECODE=IIF(MIN(SOURCECODE) IS NULL OR RTRIM(MIN(SOURCECODE))='',':BLANK', MIN(SOURCECODE))
  FROM TBL_PLEDGEDESTINATION
  GROUP BY PLEDGEID
)
-- --------------------------------------------------------------
,cte_pledge as (
  SELECT P1.*, P2.CHK_SOURCECODE, P2.FIRST_SOURCECODE
  FROM cte_legit_pledge P1 LEFT JOIN cte_pledge_source P2 ON (P1.PLEDGEID=P2.PLEDGEID)
)
-- --------------------------------------------------------------


-- --------------------------------------------------------------
SELECT PLEDGEID, STARTDATE, ENDDATE, DESCRIPTION, PLEDGERECRUITEDBY, PLEDGESTATUS, PLEDGEPLAN, PLEDGETYPE, PAYMENTFREQUENCY, PAYMENTTYPE, INSTALMENTVALUE, CREATED, CREATEDBY
  ,CHK_SOURCECODE,FIRST_SOURCECODE
FROM cte_pledge
WHERE /*<COLMUNS>*/[DESCRIPTION]/*</COLMUNS>*/ IN (/*<SELECTION>*/':BLANK'/*</SELECTION>*/)


-- SELECT *
-- FROM(
--   SELECT /*<COLMUNS>*/[PLEDGESTATUS]/*</COLMUNS>*/,/*<ROWS>*/[DESCRIPTION]/*</ROWS>*/,COUNT([PLEDGEID]) AS CNT
--   FROM cte_legit_pledge
--   GROUP BY PLEDGESTATUS,DESCRIPTION) TBL1
--   PIVOT
--   (SUM([CNT])
--     FOR /*<COLMUNS>*/[PLEDGESTATUS]/*</COLMUNS>*/ 
--     IN (/*<COL_VALES>*/[Active],[On Hold],[Closed],[Written Down],[:BLANK]/*</COL_VALES>*/ )
--   ) TBL2

-- SELECT
--   p1.PLEDGEID
--   ,p1.PLEDGESTATUS
--   ,p1.PLEDGEPLAN
--   ,p1.PLEDGETYPE
--   ,p1.PAYMENTFREQUENCY
--   ,p1.PAYMENTTYPE
--   ,p1.STARTDATE
--   ,p1.DESCRIPTION
--   ,p1.EXTERNALREF
--   ,p1.EXTERNALREFTYPE
-- FROM
--   cte_legit_pledge p1
-- WHERE 1=1
--   -- AND CAST(p1.CREATED AS DATE) >= DATEFROMPARTS(2017,7,1)
--   -- AND p1.PLEDGEPLAN = 'Regular'
--   -- AND p1.PLEDGETYPE = 'Non Regular Payment'
--   -- AND p1.PAYMENTFREQUENCY is Null
-- ORDER BY
--   p1.CREATED DESC

-- -- SELECT CHK_STARTDATE, COUNT(CHK_STARTDATE) from cte_legit_pledge group by CHK_STARTDATE
-- -- SELECT distinct PLEDGEPLAN from cte_legit_pledge
-- -- SELECT distinct PLEDGETYPE from cte_legit_pledge
-- -- SELECT distinct PAYMENTFREQUENCY from cte_legit_pledge
-- -- SELECT distinct PAYMENTTYPE from cte_legit_pledge
