with
-- --------------------------------------------------------------
cte_rex_customerids AS(
  SELECT SERIALNUMBER, PARAMETERNAME, PARAMETERVALUE
    , COUNT(SERIALNUMBER) OVER (PARTITION BY PARAMETERVALUE) AS [TQID_COUNT]
  FROM TBL_CONTACTPARAMETER
  WHERE PARAMETERNAME LIKE '%Customer%Number%'
)
-- --------------------------------------------------------------
,cte_rex_firstid AS(
SELECT SERIALNUMBER
  , COUNT(PARAMETERVALUE) AS [REXID_COUNT]
  , MIN(PARAMETERVALUE) AS [REXID_FIRST]
  , MIN(TQID_COUNT) AS [TQID_COUNT]
FROM cte_rex_customerids
GROUP BY SERIALNUMBER
)
-- --------------------------------------------------------------
,cte_first_date AS(
SELECT 
  tmp.SERIALNUMBER, MIN(FIRSTDATE) AS [FIRSTDATE], MIN(FIRSTMERCHDATE) AS [FIRSTMERCHDATE]
FROM(
  SELECT B2.SERIALNUMBER
    , MIN(B2.DATEOFPAYMENT) OVER(PARTITION BY B2.SERIALNUMBER) AS [FIRSTDATE]
    , CASE WHEN S1.SOURCETYPE LIKE '%Merch%' 
      THEN 
        MIN(B2.DATEOFPAYMENT) OVER(PARTITION BY B2.SERIALNUMBER, CASE WHEN S1.SOURCETYPE LIKE '%Merch%' THEN -1 ELSE 0 END)
      ELSE NULL END AS [FIRSTMERCHDATE] 
  FROM 
    Tbl_BATCHITEMSPLIT B1
    LEFT JOIN Tbl_BATCHITEM B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
    LEFT JOIN Tbl_SOURCECODE  S1 ON (B1.SOURCECODE = S1.SOURCECODE)
  WHERE B2.REVERSED IS NULL OR NOT (B2.REVERSED IN (1,-1,2))
) tmp
GROUP BY tmp.SERIALNUMBER
)
-- --------------------------------------------------------------
select
  t1.SERIALNUMBER
  , CAST(t1.REXID_FIRST AS VARCHAR(10)) AS [REXID_FIRST]
  , t1.REXID_COUNT
  , t1.TQID_COUNT
  , t2.FIRSTDATE
  , t2.FIRSTMERCHDATE
  , c1.SORTKEYREFREL2 AS [ROLE]
  , c1.SORTKEYREF1 AS [SERIALNUMBER_REF1]
  , c1.SORTKEYREFREL1 AS [ROLE_REF1]
  , CONTACTTYPE = IIF(c1.CONTACTTYPE IS NULL OR RTRIM(c1.CONTACTTYPE )='', NULL, c1.CONTACTTYPE)
  , PRIMARYCATEGORY = IIF(c1.PRIMARYCATEGORY IS NULL OR RTRIM(c1.PRIMARYCATEGORY )='', NULL, c1.PRIMARYCATEGORY)
  , SOURCE = IIF(c1.SOURCE IS NULL OR RTRIM(c1.SOURCE )='', NULL, c1.SOURCE)
  , GENDER = IIF(c1.GENDER IS NULL OR RTRIM(c1.GENDER )='', NULL, c1.GENDER)
  , STATE= CAST(
      IIF(UPPER(LTRIM(RTRIM(c1.ADDRESSLINE4))) IN ('VIC','NSW','SA','QLD','WA','TAS','ACT','NT'),UPPER(LTRIM(RTRIM(c1.ADDRESSLINE4)))
        ,IIF(RTRIM(c1.ADDRESSLINE4)='' OR c1.ADDRESSLINE4 IS NULL, NULL,'O/S')) AS VARCHAR(6))
  , AGE = IIF(c1.DATEOFBIRTH IS NULL OR RTRIM(c1.DATEOFBIRTH )='', NULL, (DATEDIFF(day,c1.DATEOFBIRTH,CURRENT_TIMESTAMP)+1)/365)
  , FULLNAME = CONCAT(
    IIF(RTRIM(c1.TITLE)='' OR c1.TITLE IS NULL,'',RTRIM(c1.TITLE)+' ')
    ,IIF(RTRIM(c1.FIRSTNAME)='' OR c1.FIRSTNAME IS NULL,'',RTRIM(c1.FIRSTNAME)+' ')
    ,IIF(RTRIM(c1.OTHERINITIAL)='' OR c1.OTHERINITIAL IS NULL,'',RTRIM(c1.OTHERINITIAL)+' '),c1.KEYNAME)
  , DONOTCALL = IIF(c2.DONOTCALL=-1,'YES',NULL)
  , DONOTEMAIL = IIF(c2.DONOTEMAIL=-1,'YES',NULL)
  , DONOTMAIL = IIF(c1.DONOTMAIL=-1,'YES',NULL)
  , MAJORDONOR = IIF(c1.MAJORDONOR = -1,'YES',NULL)
  , CURRENT_TIMESTAMP AS CURRENTTIMESTAMP
from
  cte_rex_firstid t1
  left join TBL_CONTACT c1 ON (t1.SERIALNUMBER = c1.SERIALNUMBER)
  LEFT JOIN TBL_CONTACTATTRIBUTE c2 ON (c1.SERIALNUMBER = c2.SERIALNUMBER)
  left join cte_first_date t2  ON (t1.SERIALNUMBER = t2.SERIALNUMBER)
where
  c1.CONTACTTYPE <> 'ADDRESS'
