-- use thankQ4_Reporter;
with
-- --------------------------------------------------------------
ones AS (
	SELECT * FROM (VALUES (0), (1), (2), (3), (4),(5), (6), (7), (8), (9)) AS numbers(x)
)
-- --------------------------------------------------------------
,generation_def AS (
   SELECT * FROM (
      VALUES
      (0,1824,'ANCIENT','01.AC')
      ,(1825,1844,'EARLY COLONIAL','02.EC')
      ,(1845,1864,'MID COLONIAL','03.MC')
      ,(1865,1884,'LATE COLONIAL','04.LC')
      ,(1885,1904,'HARD TIMERS','05.HT')
      ,(1905,1924,'FEDERATION','06.F')
      ,(1925,1944,'SILENT','07.S')
      ,(1945,1964,'BABY BOOMERS','08.BB')
      ,(1965,1979,'GENERATION X','09.X')
      ,(1980,1994,'GENERATION Y','10.Y')
      ,(1995,2009,'GENERATION Z','11.Z')
      ,(2010,9999,'MILLENIALS','12.M')
      ) AS generation(y1,y2,gen,gen_abr) 
)
-- --------------------------------------------------------------
,cte_generation AS(
SELECT cy=n.x,gen=g.gen,gen_abr=g.gen_abr
FROM 
   (SELECT x=1000*o1000.x + 100*o100.x + 10*o10.x + o1.x FROM ones o1, ones o10, ones o100, ones o1000 ) n 
   LEFT JOIN generation_def g on(n.x>=g.y1 AND n.x<=g.y2)
WHERE n.x BETWEEN 1 AND YEAR(CURRENT_TIMESTAMP)
)
-- --------------------------------------------------------------
,cte_clean_contact AS (
SELECT C1.SERIALNUMBER
   ,CONTACT = CONCAT(
      IIF(RTRIM(C1.TITLE)='' OR C1.TITLE IS NULL,'',RTRIM(C1.TITLE)+' ')
      ,IIF(RTRIM(C1.FIRSTNAME)='' OR C1.FIRSTNAME IS NULL,'',RTRIM(C1.FIRSTNAME)+' ')
      ,IIF(RTRIM(C1.OTHERINITIAL)='' OR C1.OTHERINITIAL IS NULL,'',RTRIM(C1.OTHERINITIAL)+' '),C1.KEYNAME)
   ,CONTACTTYPE = IIF(C1.CONTACTTYPE IS NULL OR RTRIM(C1.CONTACTTYPE )='','[DNF]',C1.CONTACTTYPE)
   ,PRIMARYCATEGORY = IIF(C1.PRIMARYCATEGORY IS NULL OR RTRIM(C1.PRIMARYCATEGORY )='','[DNF]',C1.PRIMARYCATEGORY)
   ,CONTACTSOURCE = IIF(C1.SOURCE IS NULL OR RTRIM(C1.SOURCE )='','[DNF]',C1.SOURCE)
   ,GENDER = IIF(C1.CONTACTTYPE='Organisation' AND (C1.GENDER IS NULL OR RTRIM(C1.GENDER )=''),'[N/A]',IIF(C1.GENDER IS NULL OR RTRIM(C1.GENDER )='','[DNF]',C1.GENDER ))
   ,C1.DATEOFBIRTH
   ,AGE = IIF(C1.DATEOFBIRTH IS NULL OR RTRIM(C1.DATEOFBIRTH )='',NULL,(DATEDIFF(day,C1.DATEOFBIRTH,CURRENT_TIMESTAMP)+1)/365)
   ,GENERATION = IIF((C1.DATEOFBIRTH IS NULL OR RTRIM(C1.DATEOFBIRTH)=''),'[DNF]',C3.GEN)
   ,GENERATIONCODE = IIF((C1.DATEOFBIRTH IS NULL OR RTRIM(C1.DATEOFBIRTH)=''),'[DNF]',C3.GEN_ABR)
   ,SUBURB = IIF(C1.ADDRESSLINE3 IS NULL OR RTRIM(C1.ADDRESSLINE3 )='','[DNF]',C1.ADDRESSLINE3)
   ,STATE = IIF(C1.ADDRESSLINE4 IS NULL OR RTRIM(C1.ADDRESSLINE4 )='','[DNF]',C1.ADDRESSLINE4)
   ,STATEAU = IIF(UPPER(LTRIM(RTRIM(C1.ADDRESSLINE4))) IN ('VIC','NSW','SA','QLD','WA','TAS','ACT','NT'),UPPER(LTRIM(RTRIM(C1.ADDRESSLINE4))),IIF(RTRIM(C1.ADDRESSLINE4)='' OR C1.ADDRESSLINE4 IS NULL,'[DNF]','O/S'))
   ,POSTCODE = LTRIM(RTRIM(C1.POSTCODE))
   ,COUNTRY = IIF(C1.COUNTRY IS NULL OR RTRIM(C1.COUNTRY )='','[DNF]',C1.COUNTRY)
   ,EMAIL = IIF(C1.EMAILADDRESS IS NULL OR RTRIM(C1.EMAILADDRESS )='',NULL,C1.EMAILADDRESS)
   ,DECEASED = IIF(C1.DONOTMAILREASON LIKE '%Deceased%','YES',NULL)
   ,DECEASEDDATE = IIF(C1.DONOTMAILREASON LIKE '%Deceased%',C1.DONOTMAILFROM,NULL)
   ,ESTATE = IIF(C1.PRIMARYCATEGORY LIKE '%ESTATE%','YES',NULL)
   ,MAJORDONOR = IIF(C1.MAJORDONOR = -1,'YES',NULL)
   ,ANONYMOUS = IIF(C1.ANONYMOUS=-1,'YES',NULL)
   ,DONOTCALL = IIF(C2.DONOTCALL=-1,'YES',NULL)
   ,DONOTMAIL = IIF(C1.DONOTMAIL=-1,'YES',NULL)
   ,DONOTMAILREASON = IIF(C1.DONOTMAIL=-1,IIF(C1.DONOTMAILREASON IS NULL OR RTRIM(C1.DONOTMAILREASON)='','[DNF]',C1.DONOTMAILREASON),'[N/A]')
   ,C1.CREATED
   ,CREATEDBY = IIF(C1.CREATEDBY IS NULL OR RTRIM(C1.CREATEDBY )='','[DNF]',C1.CREATEDBY)
FROM
   TBL_CONTACT C1
   LEFT JOIN TBL_CONTACTATTRIBUTE C2 ON (C1.SERIALNUMBER = C2.SERIALNUMBER)
   LEFT JOIN cte_generation C3 ON (YEAR(C1.DATEOFBIRTH) = C3.cy)
WHERE C1.CONTACTTYPE <> 'ADDRESS'
)
-- --------------------------------------------------------------
,cte_cureone_journey_communication AS (
   SELECT SERIALNUMBER
      ,CATEGORY,CREATEDBY,DATEOFCOMMUNICATION,COMMUNICATIONTYPE
      ,JOURNEY_VERSION = IIF(CATEGORY IS NULL OR RTRIM(CATEGORY) = '' OR UPPER(LEFT(CATEGORY,8))<>'CURE ONE',NULL,IIF(ISNUMERIC(RTRIM(RIGHT(CATEGORY,4)))=1,RIGHT(CATEGORY,4),NULL))
      ,JOURNEY_STAGE = 
      IIF(PATINDEX('%WELCOME%',UPPER(SUBJECT)) > 0 OR PATINDEX('%WELCOME%PACK%',UPPER(SUBJECT)) > 0
            ,'WELCOME PACK',
            IIF(PATINDEX('%THANK%YOU%',UPPER(SUBJECT)) > 0
            ,'THANK YOU',
                  IIF(PATINDEX('%RESTORE%PACK%',UPPER(SUBJECT)) > 0 OR PATINDEX('%RENEW%PACK%',UPPER(SUBJECT)) > 0
                  ,'RR PACK',
                        IIF(PATINDEX('%CARE%PACK%',UPPER(SUBJECT)) > 0
                        ,'CARE PACK',
                              IIF(CHARINDEX('CURE PACK',UPPER(SUBJECT)) > 0 OR CHARINDEX('CUREPACK',UPPER(SUBJECT)) > 0
                              ,'CURE PACK',
                                    IIF(PATINDEX('%1ST%CALL%',UPPER(SUBJECT)) > 0 AND UPPER(COMMUNICATIONTYPE) = 'PHONE CALL'
                                    ,'RESTORED CALL1',
                                          IIF(PATINDEX('%2ND%CALL%',UPPER(SUBJECT)) > 0 AND UPPER(COMMUNICATIONTYPE) = 'PHONE CALL'
                                          ,'RESTORED CALL2',
                                                IIF(PATINDEX('%CHRISTMAS%',UPPER(SUBJECT)) > 0 AND UPPER(COMMUNICATIONTYPE) = 'CARD'
                                                ,'CHRISTMAS CARD'
                                                ,'OTHER'))))))))
      ,SUBJECT,NOTES
      FROM TBL_COMMUNICATION
      WHERE CATEGORY LIKE 'Cure One%'
)
-- --------------------------------------------------------------
,cte_cureone_journey_profiles AS (
   SELECT 
      D2.SERIALNUMBER
      -- ,CONTACT = CONCAT(
      --    IIF(RTRIM(D1.TITLE)='' OR D1.TITLE IS NULL,'',RTRIM(D1.TITLE)+' ')
      --    ,IIF(RTRIM(D1.FIRSTNAME)='' OR D1.FIRSTNAME IS NULL,'',RTRIM(D1.FIRSTNAME)+' ')
      --    ,IIF(RTRIM(D1.OTHERINITIAL)='' OR D1.OTHERINITIAL IS NULL,'',RTRIM(D1.OTHERINITIAL)+' '),D1.KEYNAME)

      ,JOURNEY_CATEGORY = D2.PARAMETERNAME
      ,JOURNEY_NAME = IIF(D2.PARAMETERVALUE IS NULL OR RTRIM(D2.PARAMETERVALUE) = '','[DNF]',D2.PARAMETERVALUE)
      ,JOURNEY_VERSION = IIF(D2.PARAMETERVALUE IS NULL OR RTRIM(D2.PARAMETERVALUE) = '',NULL,IIF(ISNUMERIC(RTRIM(LEFT(D2.PARAMETERVALUE,4)))=1,LEFT(D2.PARAMETERVALUE,4),NULL))
      ,JOURNEY_TYPE = IIF(D2.PARAMETERVALUE IS NULL OR RTRIM(D2.PARAMETERVALUE) = '','[DNF]',IIF(D2.PARAMETERVALUE LIKE '%Renewal%','Renewal','Normal'))
      ,JOURNEY_FREQUENCY = IIF(D2.PARAMETERVALUE IS NULL OR RTRIM(D2.PARAMETERVALUE) = '','[DNF]',IIF(D2.PARAMETERVALUE LIKE '%Monthly%','Monthly',IIF(D2.PARAMETERVALUE LIKE '%Yearly%','Yearly','Other')))
      -- Defination of the Cure one Journey : There're 3 Key Actions to take in these journey, which will happen after 2,5 and 10 months respectively 
      ,JOURNEY_STRUCTURE = 
            IIF(D2.EFFECTIVEFROM IS NOT NULL AND RTRIM(D2.EFFECTIVEFROM)<>'' AND D2.EFFECTIVETO IS NOT NULL AND RTRIM (D2.EFFECTIVETO)<>'' AND CAST(D2.EFFECTIVEFROM AS DATE) <= CAST(D2.EFFECTIVETO AS DATE)
                  ,IIF(
                        CAST(D2.EFFECTIVEFROM AS DATE) = CAST(D2.EFFECTIVETO AS DATE)
                        ,'No Journey'
                        ,IIF(
                              DATEADD(month,2,D2.EFFECTIVEFROM) <= D2.EFFECTIVETO
                              AND DATEADD(month,5,D2.EFFECTIVEFROM) <= D2.EFFECTIVETO 
                              AND DATEADD(month,10,D2.EFFECTIVEFROM) <= D2.EFFECTIVETO
                              ,'Full Journey'
                              ,'Partial Journey'))
                  ,'Invaild Journey')
      ,JOURNEY_STATUS =
            IIF(D2.EFFECTIVEFROM IS NOT NULL AND RTRIM(D2.EFFECTIVEFROM)<>'' AND D2.EFFECTIVETO IS NOT NULL AND RTRIM(D2.EFFECTIVETO)<>'' AND CAST(D2.EFFECTIVEFROM AS DATE) <= CAST(D2.EFFECTIVETO AS DATE),
                  IIF(CURRENT_TIMESTAMP >= CONVERT(DATE, D2.EFFECTIVEFROM) AND CURRENT_TIMESTAMP <= CONVERT(DATE, D2.EFFECTIVETO)
                        ,'Active'
                        ,IIF(CURRENT_TIMESTAMP < D2.EFFECTIVEFROM
                              ,'Wait'
                              ,IIF(CURRENT_TIMESTAMP > D2.EFFECTIVETO
                                    ,'Finished'
                                    ,'Invaild')))
                  ,'Invaild')
      ,TODAYDUE = IIF(CAST(CURRENT_TIMESTAMP AS DATE) = D2.EFFECTIVEFROM AND D2.EFFECTIVEFROM <= D2.EFFECTIVETO, 'WelcomePack',
            IIF(CAST(CURRENT_TIMESTAMP AS DATE) = DATEADD(month,2,D2.EFFECTIVEFROM) AND DATEADD(month,2,D2.EFFECTIVEFROM) <= D2.EFFECTIVETO, 'Cure Pack 3',
               IIF(CAST(CURRENT_TIMESTAMP AS DATE) = DATEADD(month,5,D2.EFFECTIVEFROM) AND DATEADD(month,5,D2.EFFECTIVEFROM) <= D2.EFFECTIVETO, 'Care Pack 5',
                  IIF(CAST(CURRENT_TIMESTAMP AS DATE) = DATEADD(month,10,D2.EFFECTIVEFROM) AND DATEADD(month,10,D2.EFFECTIVEFROM) <= D2.EFFECTIVETO, 'Restore & Renew Pack 11',NULL))))
      ,NEXTDUE = 
         IIF(CAST(CURRENT_TIMESTAMP AS DATE) <= D2.EFFECTIVEFROM AND D2.EFFECTIVEFROM < D2.EFFECTIVETO, D2.EFFECTIVEFROM,
            IIF(CAST(CURRENT_TIMESTAMP AS DATE) <= DATEADD(month,2,D2.EFFECTIVEFROM) AND DATEADD(month,2,D2.EFFECTIVEFROM) <= D2.EFFECTIVETO, DATEADD(month,2,D2.EFFECTIVEFROM),
               IIF(CAST(CURRENT_TIMESTAMP AS DATE) <= DATEADD(month,5,D2.EFFECTIVEFROM) AND DATEADD(month,5,D2.EFFECTIVEFROM) <= D2.EFFECTIVETO, DATEADD(month,5,D2.EFFECTIVEFROM),
                  IIF(CAST(CURRENT_TIMESTAMP AS DATE) <= DATEADD(month,10,D2.EFFECTIVEFROM) AND DATEADD(month,10,D2.EFFECTIVEFROM) <= D2.EFFECTIVETO, DATEADD(month,10,D2.EFFECTIVEFROM),
                     IIF(CAST(CURRENT_TIMESTAMP AS DATE) <= 
                           IIF(D2.EFFECTIVEFROM < D2.EFFECTIVETO AND D2.EFFECTIVEFROM <= DATEFROMPARTS(YEAR(D2.EFFECTIVEFROM),12,1), DATEFROMPARTS(YEAR(D2.EFFECTIVEFROM),12,1), IIF(D2.EFFECTIVEFROM < D2.EFFECTIVETO AND D2.EFFECTIVETO >= DATEFROMPARTS(YEAR(D2.EFFECTIVETO),12,1),DATEFROMPARTS(YEAR(D2.EFFECTIVETO),12,1),NULL)) 
                        AND D2.EFFECTIVETO >=
                           IIF(D2.EFFECTIVEFROM < D2.EFFECTIVETO AND D2.EFFECTIVEFROM <= DATEFROMPARTS(YEAR(D2.EFFECTIVEFROM),12,1), DATEFROMPARTS(YEAR(D2.EFFECTIVEFROM),12,1), IIF(D2.EFFECTIVEFROM < D2.EFFECTIVETO AND D2.EFFECTIVETO >= DATEFROMPARTS(YEAR(D2.EFFECTIVETO),12,1),DATEFROMPARTS(YEAR(D2.EFFECTIVETO),12,1),NULL))
                        , 
                        IIF(D2.EFFECTIVEFROM < D2.EFFECTIVETO AND D2.EFFECTIVEFROM <= DATEFROMPARTS(YEAR(D2.EFFECTIVEFROM),12,1), DATEFROMPARTS(YEAR(D2.EFFECTIVEFROM),12,1), IIF(D2.EFFECTIVEFROM < D2.EFFECTIVETO AND D2.EFFECTIVETO >= DATEFROMPARTS(YEAR(D2.EFFECTIVETO),12,1),DATEFROMPARTS(YEAR(D2.EFFECTIVETO),12,1),NULL))
                        ,
                     NULL)))))
      -- Start of Journey Road Map
      ,JOURNEY_START = D2.EFFECTIVEFROM
      ,CHRISTMASCARD_DUE = CAST(IIF(D2.EFFECTIVEFROM < D2.EFFECTIVETO AND D2.EFFECTIVEFROM <= DATEFROMPARTS(YEAR(D2.EFFECTIVEFROM),12,1), DATEFROMPARTS(YEAR(D2.EFFECTIVEFROM),12,1)
         , IIF(D2.EFFECTIVEFROM < D2.EFFECTIVETO AND D2.EFFECTIVETO >= DATEFROMPARTS(YEAR(D2.EFFECTIVETO),12,1),DATEFROMPARTS(YEAR(D2.EFFECTIVETO),12,1),NULL)) AS DATE)
      
      ,WELCOMEPACK_DUE = IIF(D2.EFFECTIVEFROM < D2.EFFECTIVETO, D2.EFFECTIVEFROM , NULL)
      ,CURE_PACK3_DUE = IIF(DATEADD(month,2,D2.EFFECTIVEFROM) <= D2.EFFECTIVETO, DATEADD(month,2,D2.EFFECTIVEFROM) , NULL)
      ,CARE_PACK6_DUE = IIF(DATEADD(month,5,D2.EFFECTIVEFROM) <= D2.EFFECTIVETO, DATEADD(month,5,D2.EFFECTIVEFROM) , NULL)
      ,RR_PACK11_DUE = IIF(DATEADD(month,10,D2.EFFECTIVEFROM) <= D2.EFFECTIVETO, DATEADD(month,10,D2.EFFECTIVEFROM) , NULL)
      ,RESTORED_CALL1_DUE = IIF(DATEADD(day,14,DATEADD(month,10,D2.EFFECTIVEFROM)) <= D2.EFFECTIVETO, DATEADD(day,14,DATEADD(month,10,D2.EFFECTIVEFROM)) , NULL)
      ,RESTORED_CALL2_DUE = IIF(DATEADD(day,15,DATEADD(month,10,D2.EFFECTIVEFROM)) <= D2.EFFECTIVETO, DATEADD(day,15,DATEADD(month,10,D2.EFFECTIVEFROM)) , NULL)
      
      ,JOURNEY_END = D2.EFFECTIVETO
      -- End of Journey Road Map
      
      -- ,THANKYOUCALL_ACT = NULL
      -- ,CHRISTMASCARD_ACT = NULL
      -- ,WELCOMEPACK_ACT = NULL
      -- ,CURE_PACK3_ACT = NULL
      -- ,CARE_PACK6_ACT = NULL
      -- ,RR_PACK11_ACT = NULL
      -- ,RESTORED_CALL1_ACT = NULL
      -- ,RESTORED_CALL2_ACT = NULL

      ,JOURNEYNOTE = D2.PARAMETERNOTE
   FROM
      TBL_CONTACTPARAMETER D2 
      -- LEFT JOIN TBL_CONTACT D1 ON (D1.SERIALNUMBER = D2.SERIALNUMBER)
   WHERE
      D2.PARAMETERNAME LIKE ('%Cure%One%' + '%Journey%')
)
-- --------------------------------------------------------------
,cte_cureone_journeies_by_donor AS (
   SELECT SERIALNUMBER,JOURNEY_VERSION,CUREONEJOURNEIES = COUNT(SERIALNUMBER)
   FROM cte_cureone_journey_profiles
   GROUP BY SERIALNUMBER,JOURNEY_VERSION
)
-- --------------------------------------------------------------
,cte_cureone_journey AS (
   SELECT
      [SERIALNUMBER],[CONTACT]
      ,[JOURNEY_CATEGORY],[JOURNEY_VERSION],[JOURNEY_VERSION_UNIQUE],[JOURNEY_TYPE],[JOURNEY_FREQUENCY],[JOURNEY_STATUS],[JOURNEY_STRUCTURE]
      ,[TODAY] = IIF([NEXTDUE] IS NULL,NULL, IIF(CAST([NEXTDUE] AS DATE) = CAST(CURRENT_TIMESTAMP AS DATE), [NEXTDUE], NULL))
      ,[NEXTDUE]
      ,[JOURNEY_START]
      ,[WELCOMEPACK_DUE]
      ,[CURE_PACK3_DUE]
      ,[CARE_PACK6_DUE]
      ,[RR_PACK11_DUE]
      ,[RESTORED_CALL1_DUE]
      ,RESTORED_CALL2_DUE = IIF([RESTORED CALL1]>0,NULL, [RESTORED_CALL2_DUE])
      ,[CHRISTMASCARD_DUE]
      ,[JOURNEY_END]
      ,[THANK YOU],[CHRISTMAS CARD],[WELCOME PACK],[CURE PACK],[CARE PACK],[RR PACK],[RESTORED CALL1],[RESTORED CALL2],[OTHER]
   FROM
   (
      SELECT
         CJ1.SERIALNUMBER,CJ3.CONTACT
         ,CJ1.JOURNEY_CATEGORY
         ,CJ1.JOURNEY_VERSION
         ,JOURNEY_VERSION_UNIQUE = IIF(CJ4.CUREONEJOURNEIES=1,'YES','NO')
         ,CJ1.JOURNEY_TYPE,CJ1.JOURNEY_FREQUENCY,CJ1.JOURNEY_STATUS,CJ1.JOURNEY_STRUCTURE

         ,CJ1.NEXTDUE
         ,CJ1.JOURNEY_START
         ,CJ1.WELCOMEPACK_DUE
         ,CJ1.CURE_PACK3_DUE
         ,CJ1.CARE_PACK6_DUE
         ,CJ1.RR_PACK11_DUE
         ,CJ1.RESTORED_CALL1_DUE
         ,RESTORED_CALL2_DUE = CJ1.RESTORED_CALL2_DUE
         ,CJ1.CHRISTMASCARD_DUE
         ,CJ1.JOURNEY_END

         ,CJ2.JOURNEY_STAGE
      FROM
         cte_cureone_journey_profiles CJ1
         LEFT JOIN cte_cureone_journey_communication CJ2 ON (CJ1.SERIALNUMBER = CJ2.SERIALNUMBER AND CJ1.JOURNEY_VERSION = CJ2.JOURNEY_VERSION)
         LEFT JOIN cte_clean_contact CJ3 ON (CJ1.SERIALNUMBER = CJ3.SERIALNUMBER)
         LEFT JOIN cte_cureone_journeies_by_donor CJ4 ON (CJ1.SERIALNUMBER = CJ4.SERIALNUMBER AND CJ1.JOURNEY_VERSION = CJ4.JOURNEY_VERSION)
   ) DATA_TABLE
   PIVOT
   (
         COUNT(JOURNEY_STAGE)
         FOR JOURNEY_STAGE IN ([THANK YOU],[CHRISTMAS CARD],[WELCOME PACK],[CURE PACK],[CARE PACK],[RR PACK],[RESTORED CALL1],[RESTORED CALL2],[OTHER])
   ) PIVOT_TABLE

)
-- --------------------------------------------------------------
select * 
from cte_cureone_journey
order by TODAY DESC
