
  SELECT
--     RTRIM(C1.SERIALNUMBER) AS [SN]
    C1.SERIALNUMBER AS [SN]
    ,C1.CREATED AS [CONTACT_CREATED]
    ,CONCAT(
      CASE WHEN RTRIM(C1.TITLE)='' OR C1.TITLE IS NULL THEN '' ELSE TRIM(C1.TITLE) + ' ' END,
      CASE WHEN RTRIM(C1.FIRSTNAME)='' OR C1.FIRSTNAME IS NULL THEN '' ELSE TRIM(C1.FIRSTNAME) + ' ' END,
      CASE WHEN RTRIM(C1.OTHERINITIAL)='' OR C1.OTHERINITIAL IS NULL THEN '' ELSE TRIM(C1.OTHERINITIAL) + ' ' END,
      RTRIM(C1.KEYNAME)
    ) AS [CONTACT_FULLNAME]
    , C1.CONTACTTYPE, C1.PRIMARYCATEGORY, C1.SOURCE
    , C1.GENDER
    , C1.DATEOFBIRTH
    , (DATEDIFF(day, C1.DATEOFBIRTH, CURRENT_TIMESTAMP)+1)/365 AS [AGE]
    , C1.ADDRESSLINE1, C1.ADDRESSLINE2, C1.ADDRESSLINE3 AS [SUBURB]
    , UPPER(LTRIM(RTRIM(C1.ADDRESSLINE4))) AS [STATE]
    , CASE WHEN C1.ADDRESSLINE4 IS NULL OR RTRIM(C1.ADDRESSLINE4) = ''
      THEN -- TYPE1 (When State is blank)
        CASE WHEN C1.COUNTRY IS NULL OR RTRIM(C1.COUNTRY) = '' OR ( UPPER(LEFT(LTRIM(C1.COUNTRY), 2)) = 'AU' AND UPPER(LTRIM(RTRIM(C1.COUNTRY))) <> 'AUSTRIA' )
        THEN 'MISSING'
        ELSE 'O/S'
        END
      ELSE
        CASE WHEN UPPER(LTRIM(RTRIM(C1.ADDRESSLINE4))) IN ('VIC','NSW','SA','QLD','WA','TAS','ACT','NT')
        THEN -- TYPE2 (When State is AU)
          CASE WHEN C1.COUNTRY IS NULL OR RTRIM(C1.COUNTRY) = '' OR ( UPPER(LEFT(LTRIM(C1.COUNTRY), 2)) = 'AU' AND UPPER(LTRIM(RTRIM(C1.COUNTRY))) <> 'AUSTRIA' )
          THEN UPPER(LTRIM(RTRIM(C1.ADDRESSLINE4)))
          ELSE 'O/S'
          END
        ELSE -- TYPE3 (When State is Non-AU)
          CASE WHEN C1.COUNTRY IS NULL OR RTRIM(C1.COUNTRY) = '' OR ( UPPER(LEFT(LTRIM(C1.COUNTRY), 2)) <> 'AU' OR UPPER(LTRIM(RTRIM(C1.COUNTRY))) = 'AUSTRIA' )
          THEN 'O/S'
          ELSE 'ERROR'
          END
        END
      END AS [STATECOUNTRY]
    , C1.POSTCODE
    , UPPER(LTRIM(RTRIM(C1.COUNTRY))) AS [COUNTRY]

    , C1.DONOTMAILREASON, C1.DONOTMAILFROM, C1.DONOTMAILUNTIL
    -- Filters
    , CASE WHEN C1.CONTACTTYPE='Organisation' THEN -1 ELSE 0 END AS [FILTER_ORGANISATION]
    , CASE WHEN C1.CONTACTTYPE='Organisation'
      THEN 1
      ELSE
        CASE WHEN C1.GENDER IS NULL OR RTRIM(C1.GENDER) = ''
        THEN 0
        ELSE CASE WHEN UPPER(LTRIM(RTRIM(C1.GENDER))) = 'MALE' THEN -1 ELSE -2 END
        END
      END AS [FILTER_GENDER]
    , CASE WHEN C1.MAJORDONOR = -1 THEN -1 ELSE 0 END AS [FILTER_MAJDONOR]
    , CASE WHEN C1.ANONYMOUS = -1 THEN -1 ELSE 0 END AS [FILTER_ANONYMOUS]
    , CASE WHEN C1.DONOTMAIL = -1 THEN -1 ELSE 0 END AS [FILTER_DONOTMAIL]
    , CASE WHEN C1.DONOTMAIL = -1 AND C1.DONOTMAILREASON LIKE '%DECEASED%' THEN -1 ELSE 0 END AS [FILTER_DECEASED]
    , CASE WHEN C1.PRIMARYCATEGORY LIKE '%estate%' THEN -1 ELSE 0 END AS [FILTER_ESTATE]
    , CASE WHEN RTRIM(C1.EMAILADDRESS) = '' OR C1.EMAILADDRESS IS NULL THEN 0 ELSE -1 END AS [FILTER_EMAIL]
    , CASE WHEN RTRIM(C1.TWITTERHANDLE) = '' OR C1.TWITTERHANDLE IS NULL THEN 0 ELSE -1 END AS [FILTER_TWITTER]
    , CASE WHEN RTRIM(C1.FACEBOOKURL) = '' OR C1.FACEBOOKURL IS NULL THEN 0 ELSE -1 END AS [FILTER_FACEBOOK]
    , CASE WHEN RTRIM(C1.LINKEDINURL) = '' OR C1.LINKEDINURL IS NULL THEN 0 ELSE -1 END AS [FILTER_LINKEDIN]
    , CASE WHEN (C1.MOBILENUMBER IS NOT NULL AND RTRIM(C1.MOBILENUMBER) <> '')
        OR (C1.DAYTELEPHONE IS NOT NULL AND RTRIM(C1.MOBILENUMBER) <> '')
        OR (C1.EVENINGTELEPHONE IS NOT NULL AND RTRIM(C1.MOBILENUMBER) <> '')
      THEN -1 ELSE 0 END AS [FILTER_PHONENUMBER]
  FROM
    TBL_CONTACT C1
  WHERE CONTACTTYPE <> 'ADDRESS'

