;
WITH
cte_payments AS(
  SELECT
    B1.SERIALNUMBER,
    B2.DATEOFPAYMENT,
    B1.PAYMENTAMOUNT,
    B1.SOURCECODE,
    S1.SOURCETYPE,
    CASE WHEN B2.REVERSED=2
    THEN 0
    ELSE DENSE_RANK() OVER(PARTITION BY CASE WHEN B2.REVERSED IN (1, -1, 2) THEN 0 ELSE -1 END ORDER BY CONCAT(CONVERT(VARCHAR(10), B2.DATEOFPAYMENT, 112), B2.SERIALNUMBER, B2.ADMITNAME, B2.RECEIPTNO) ASC)
    END AS [TRANSACTION ID]
  FROM
    TBL_BATCHITEMSPLIT            B1
    LEFT JOIN TBL_BATCHITEM       B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
    LEFT JOIN TBL_BATCHITEMPLEDGE B3 ON (B1.SERIALNUMBER = B3.SERIALNUMBER) AND (B1.RECEIPTNO = B3.RECEIPTNO) AND (B1.ADMITNAME = B3.ADMITNAME) AND (B1.LINEID = B3.LINEID)
    LEFT JOIN TBL_BATCHHEADER     B4 ON (B2.ADMITNAME = B4.ADMITNAME)
    LEFT JOIN Tbl_SOURCECODE      S1 ON (B1.SOURCECODE = S1.SOURCECODE)
  WHERE
    (B2.REVERSED IS NULL OR NOT(B2.REVERSED IN (1, -1)))
    AND (B4.STAGE ='Batch Approved')
    AND B2.DATEOFPAYMENT BETWEEN '20120701' AND CURRENT_TIMESTAMP
)
-- ---------------------------------------------------------------------------------

select
  t1.SERIALNUMBER,
  CONCAT(
    CASE WHEN RTRIM(ISNULL(t2.TITLE,''))='' THEN '' ELSE RTRIM(t2.TITLE) + ' ' END
    ,CASE WHEN RTRIM(ISNULL(t2.FIRSTNAME,''))='' THEN '' ELSE RTRIM(t2.FIRSTNAME) + ' ' END
    ,CASE WHEN RTRIM(ISNULL(t2.OTHERINITIAL,''))='' THEN '' ELSE RTRIM(t2.OTHERINITIAL) + ' ' END
    ,CASE WHEN RTRIM(ISNULL(t2.KEYNAME,''))='' THEN '' ELSE RTRIM(t2.KEYNAME) END
  ) AS [FULL NAME],
  t1.DATEOFPAYMENT AS [TRANSACTION DATE],
  SUM(t1.PAYMENTAMOUNT) AS [TRANSACTION TOTAL],
  SUM(CASE WHEN t1.SOURCETYPE like '%Merchandise%' THEN t1.PAYMENTAMOUNT ELSE 0 END) AS [MERCHANDISE TOTAL],
  SUM(CASE WHEN t1.SOURCETYPE like '%Merchandise%' THEN 0 ELSE t1.PAYMENTAMOUNT END) AS [NON-MERCHANDISE TOTAL],
  t1.[TRANSACTION ID]
from 
  cte_payments t1
  left join tbl_contact t2 on (t1.SERIALNUMBER = t2.SERIALNUMBER)
group by 
  t1.SERIALNUMBER, t1.DATEOFPAYMENT, t1.[TRANSACTION ID]
  ,t2.TITLE, t2.FIRSTNAME, t2.OTHERINITIAL, t2.KEYNAME
Having
  SUM(CASE WHEN t1.SOURCETYPE like '%Merchandise%' THEN t1.PAYMENTAMOUNT ELSE 0 END) > 0