WITH
cte_rex_customerid AS(
SELECT SERIALNUMBER
  , [PARAMETERNAME] = MIN(PARAMETERNAME)
  , [PARAMETERVALUE] = MIN(PARAMETERVALUE)
FROM TBL_CONTACTPARAMETER
WHERE PARAMETERNAME LIKE '%Customer%Number%'
GROUP BY SERIALNUMBER
)
-- ----------------------------
SELECT
  B1.SERIALNUMBER
  ,R1.PARAMETERVALUE AS [REXID]
  , FULLNAME=CONCAT(
      IIF(RTRIM(B2.TITLE)='' OR B2.TITLE IS NULL,'',RTRIM(B2.TITLE)+' ')
      ,IIF(RTRIM(B2.FIRSTNAME)='' OR B2.FIRSTNAME IS NULL,'',RTRIM(B2.FIRSTNAME)+' ')
      ,B2.KEYNAME)
  ,B2.DATEOFPAYMENT
  ,SUM(B1.PAYMENTAMOUNT) AS TOTAL
  ,S1.SOURCETYPE
  ,S1.ADDITIONALCODE3 AS CAMPAIGNCODE
  

FROM
  TBL_BATCHITEMSPLIT        B1
  LEFT JOIN TBL_BATCHITEM   B2 ON (B1.SERIALNUMBER = B2.SERIALNUMBER) AND (B1.RECEIPTNO = B2.RECEIPTNO) AND (B1.ADMITNAME = B2.ADMITNAME)
  LEFT JOIN TBL_BATCHHEADER B4 ON (B2.ADMITNAME = B4.ADMITNAME)
  LEFT JOIN TBL_SOURCECODE   S1 ON (B1.SOURCECODE = S1.SOURCECODE)
  LEFT JOIN cte_rex_customerid R1 ON (B1.SERIALNUMBER = R1.SERIALNUMBER)
WHERE
  (B2.REVERSED IS NULL OR NOT(B2.REVERSED IN (1, -1))) AND (B4.STAGE ='Batch Approved')
  AND B2.DATEOFPAYMENT BETWEEN '20171001' AND '20171231'
  AND S1.SOURCETYPE LIKE 'Merch%'
GROUP BY
  B1.SERIALNUMBER, B2.DATEOFPAYMENT, S1.SOURCETYPE, S1.ADDITIONALCODE3
  ,B2.TITLE, B2.FIRSTNAME ,B2.KEYNAME
  ,R1.PARAMETERVALUE